# SPDX-License-Identifier: CC0-1.0

libcamera_sources += files([
    'camsys/camsys.cpp',
    'camsys/capture.cpp',
    'imgsys/lpnr.cpp',
    'imgsys/imgsys.cpp',
    'imgsys/mcnr.cpp',
    'imgsys/single-device/single_device.cpp',
    'imgsys/single-device/single_device_helper.cpp',
    'imgsys/single-device/Tuning_Helper.cpp',
    'odt/imagiq_adapter/imagiq_adapter.cpp',
    'odt/on_device_tuner.cpp',
    'mtkisp7.cpp',
])
