/*
 * Copyright (C) 2022 MediaTek Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef INCLUDE_MTKCAM_INTERFACES_UTILS_NDD_NDD_AUTOGEN_DEF_H_
#define INCLUDE_MTKCAM_INTERFACES_UTILS_NDD_NDD_AUTOGEN_DEF_H_

#include <string>

using std::string;

namespace NSCam {
namespace TuningUtils {

enum class eModule {
  kAAHO,
  kAAO,
  kACTSO,
  kAE_OUT,
  kAFO,
  kAI_DEPTH,
  kAI_DEPTH_CFM,
  kAI_DEPTH_PRE_WPE,
  kAIFA,
  kAIFLASH_INFO,
  kAIHDR_DRCCORE_AE_EVD,
  kAIHDR_DRCCORE_GTM_LV,
  kAIHDR_DRCCORE_IN_APPLY_RAWIN,
  kAIHDR_DRCCORE_IN_FACEINFO,
  kAIHDR_DRCCORE_IN_NVRAM,
  kAIHDR_DRCCORE_IN_STAT_RAWIN,
  kAIHDR_DRCCORE_IN_STRUCT,
  kAIHDR_DRCCORE_LIN_TSF,
  kAIHDR_DRCCORE_OUT_APPLY_GTMT,
  kAIHDR_DRCCORE_OUT_APPLY_LTM,
  kAIHDR_DRCCORE_OUT_APPLY_RAWOUT,
  kAIHDR_HDRCORE_CONFIG,
  kAIHDR_HDRCORE_DLA_IN,
  kAIHDR_HDRCORE_DLA_OUT,
  kAIHDR_HDRCORE_INPUT_4CH_0,
  kAIHDR_HDRCORE_INPUT_4CH_1,
  kAIHDR_HDRCORE_INPUT_4CH_10,
  kAIHDR_HDRCORE_INPUT_4CH_11,
  kAIHDR_HDRCORE_INPUT_4CH_12,
  kAIHDR_HDRCORE_INPUT_4CH_13,
  kAIHDR_HDRCORE_INPUT_4CH_14,
  kAIHDR_HDRCORE_INPUT_4CH_15,
  kAIHDR_HDRCORE_INPUT_4CH_2,
  kAIHDR_HDRCORE_INPUT_4CH_3,
  kAIHDR_HDRCORE_INPUT_4CH_4,
  kAIHDR_HDRCORE_INPUT_4CH_5,
  kAIHDR_HDRCORE_INPUT_4CH_6,
  kAIHDR_HDRCORE_INPUT_4CH_7,
  kAIHDR_HDRCORE_INPUT_4CH_8,
  kAIHDR_HDRCORE_INPUT_4CH_9,
  kAIHDR_HDRCORE_OUTPUT,
  kAIHDR_MODEL_NVRAM_OUT,
  kAIMA,
  kAINR_MODEL_NVRAM,
  kAINR_NRCORE_CONFIG,
  kAINR_NRCORE_DLA_IN,
  kAINR_NRCORE_DLA_OUT,
  kAINR_NRCORE_INPUT_4CH_0,
  kAINR_NRCORE_INPUT_4CH_1,
  kAINR_NRCORE_INPUT_4CH_10,
  kAINR_NRCORE_INPUT_4CH_11,
  kAINR_NRCORE_INPUT_4CH_12,
  kAINR_NRCORE_INPUT_4CH_13,
  kAINR_NRCORE_INPUT_4CH_14,
  kAINR_NRCORE_INPUT_4CH_15,
  kAINR_NRCORE_INPUT_4CH_2,
  kAINR_NRCORE_INPUT_4CH_3,
  kAINR_NRCORE_INPUT_4CH_4,
  kAINR_NRCORE_INPUT_4CH_5,
  kAINR_NRCORE_INPUT_4CH_6,
  kAINR_NRCORE_INPUT_4CH_7,
  kAINR_NRCORE_INPUT_4CH_8,
  kAINR_NRCORE_INPUT_4CH_9,
  kAINR_NRCORE_OUTPUT,
  kAINR_TUNING_BIN,
  kAINR_UPKO,
  kAINR_WPEI,
  kAINR_WPEO,
  kAINROUTPUT,
  kAISA,
  kAISHUTTER20_HDRCORE_CONFIG,
  kAISHUTTER20_HDRCORE_DLA_IN,
  kAISHUTTER20_HDRCORE_DLA_OUT,
  kAISHUTTER20_HDRCORE_INPUT_4CH_0,
  kAISHUTTER20_HDRCORE_INPUT_4CH_1,
  kAISHUTTER20_HDRCORE_INPUT_4CH_10,
  kAISHUTTER20_HDRCORE_INPUT_4CH_11,
  kAISHUTTER20_HDRCORE_INPUT_4CH_12,
  kAISHUTTER20_HDRCORE_INPUT_4CH_13,
  kAISHUTTER20_HDRCORE_INPUT_4CH_14,
  kAISHUTTER20_HDRCORE_INPUT_4CH_15,
  kAISHUTTER20_HDRCORE_INPUT_4CH_2,
  kAISHUTTER20_HDRCORE_INPUT_4CH_3,
  kAISHUTTER20_HDRCORE_INPUT_4CH_4,
  kAISHUTTER20_HDRCORE_INPUT_4CH_5,
  kAISHUTTER20_HDRCORE_INPUT_4CH_6,
  kAISHUTTER20_HDRCORE_INPUT_4CH_7,
  kAISHUTTER20_HDRCORE_INPUT_4CH_8,
  kAISHUTTER20_HDRCORE_INPUT_4CH_9,
  kAISHUTTER20_HDRCORE_OUTPUT,
  kAISHUTTER20_IMAGESELECTION1_IN_AAHO_HIST_Y_LE_MSTM,
  kAISHUTTER20_IMAGESELECTION1_IN_AE_INFO,
  kAISHUTTER20_IMAGESELECTION1_IN_IMGSELINPUT_1,
  kAISHUTTER20_IMAGESELECTION1_IN_NVRAM,
  kAISHUTTER20_IMAGESELECTION1_IN_STRUCTURE,
  kAISHUTTER20_IMAGESELECTION1_IN_ZOOM_INFO,
  kAISHUTTER20_IMAGESELECTION1_OUT_IMGSELOUTPUT_1,
  kAISHUTTER20_IMAGESELECTION1_OUT_SHRUCTURE,
  kAISHUTTER20_IMAGESELECTION2_IN_AAHO_HIST_Y_LE_MSTM,
  kAISHUTTER20_IMAGESELECTION2_IN_AE_INFO,
  kAISHUTTER20_IMAGESELECTION2_IN_BSS_GROUP_INFO,
  kAISHUTTER20_IMAGESELECTION2_IN_IMGSELINPUT_2,
  kAISHUTTER20_IMAGESELECTION2_IN_NVRAM,
  kAISHUTTER20_IMAGESELECTION2_IN_ZOOM_INFO,
  kAISHUTTER20_IMAGESELECTION2_OUT_IMGSELOUTPUT_2,
  kAISHUTTER20_IMAGESELECTION2_OUT_SHRUCTURE,
  kAISHUTTER20_MODEL_NVRAM_OUT,
  kAISHUTTER20_MSTMCORE_IN_APPLY_RAWIN,
  kAISHUTTER20_MSTMCORE_IN_BAYER,
  kAISHUTTER20_MSTMCORE_IN_FACEINFO,
  kAISHUTTER20_MSTMCORE_IN_HDR_RATIO,
  kAISHUTTER20_MSTMCORE_IN_MSTMINPUT,
  kAISHUTTER20_MSTMCORE_IN_NVRAM,
  kAISHUTTER20_MSTMCORE_IN_NVRAMTABLE1LIST,
  kAISHUTTER20_MSTMCORE_IN_NVRAMTABLE2LIST,
  kAISHUTTER20_MSTMCORE_IN_NVRAMTABLE3LIST,
  kAISHUTTER20_MSTMCORE_IN_NVRAMTABLE4LIST,
  kAISHUTTER20_MSTMCORE_IN_NVRAMTABLE5LIST,
  kAISHUTTER20_MSTMCORE_OUT_APPLY_LTM,
  kAISHUTTER20_MSTMCORE_OUT_APPLY_RAWOUT,
  kAISHUTTER20_MSTMCORE_OUT_APPLY_TNC_STRUCTURE,
  kAISHUTTER20_MSTMCORE_OUT_MSTMOUTPUT,
  kAPU_TUNING,
  kBSS_ACTS_STAT,
  kBSS_DATAG,
  kBSS_FACES,
  kBSS_FD_INFO,
  kBSS_FD_MAIN,
  kBSS_GM,
  kBSS_IN,
  kBSS_INFO,
  kBSS_OUT,
  kBSS_PARA_BIN,
  kBSS_PARAM,
  kBSS_POS,
  kBSS_TUNING,
  kCAC,
  kCAMSV_IMGO,
  kCONF_MAP,
  kDBGBO_T1,
  kDBGO_T1,
  kDEBUGPORT,
  kDEPI,
  kDHZAI,
  kDHZAO,
  kDHZDI,
  kDHZFEBI,
  kDHZFEI,
  kDHZGI,
  kDHZGO,
  kDHZPAI,
  kDHZPGI,
  kDMGI,
  kDPEI_IMG_M,
  kDPEI_IMG_S,
  kDPEI_MASK_M,
  kDPEI_MASK_S,
  kDRZS4NO_R3,
  kDVP_ASF_ARM,
  kDVP_ASF_HF,
  kDVP_ASF_R,
  kDVP_DEPTH,
  kDVS_CFM,
  kDVS_DEPTH,
  kDVS_DV,
  kFEFM_DEC_OUT,
  kFEO,
  kFEO_D1,
  kFMB_L0,
  kFMB_L1,
  kFMB_L1_M0,
  kFMO,
  kFPRI_R1,
  kFST,
  kFW_ME_TCY_O,
  kFW_ME_TCY_P,
  kFWDHZ_LEVEL,
  kFWDHZ_LEVEL_PREV,
  kFWDHZ_MAP,
  kFWDHZ_MAP_PREV,
  kFWME_FW_FST,
  kFWME_FW_FST_P,
  kFWME_HW_FST_1PASS,
  kFWME_HW_FST_MD0,
  kFWME_HW_FST_MD0_3PASS_0,
  kFWME_HW_FST_MD1_3PASS_0,
  kFWME_MMG_FBFST,
  kFWME_MMG_RST,
  kFWME_TCY_FST,
  kFWME_WPE_FST,
  kFWMM_FBFST,
  kFWMM_GYRO_MV,
  kFWMM_HW_FMB,
  kFWMM_HW_FST,
  kFWMM_MIL,
  kFWMM_RST,
  kFWTNC_DHZ_BCE_CURV_F0,
  kFWTNC_DHZ_BCE_CURV_SL,
  kFWTNC_DHZ_BCE_FD,
  kFWTNC_DHZ_BCE_FLTCURV,
  kFWTNC_DHZ_BCE_FLTCURV_PREV,
  kFWTNC_DHZ_CROP,
  kFWTNC_DHZ_GGM_CURV,
  kFWTNC_DHZ_GTM_AE,
  kFWTNC_DHZ_GTM_CURV_PREV,
  kFWTNC_DHZ_IGGM_CURV,
  kFWTNC_DHZ_LEVEL,
  kFWTNC_DHZ_MAP,
  kGF_BLUR,
  kGF_BLUR_BOK,
  kGF_NVRAM,
  kGF_RESULT_INFO,
  kGRIDMAP,
  kGUIDE_IMG,
  kGUIDE_IMG_C,
  kGUIDE_IMG_PRE_WPE,
  kGUIDE_IMG_Y,
  kHOMO_IN,
  kHOMO_OUT,
  kHOMO_PARA,
  kIMG2BO,
  kIMG2O,
  kIMG3BO,
  kIMG3O,
  kIMG4BO,
  kIMG4O,
  kIMGBI_D1,
  kIMGBI_T1,
  kIMGCI_D1,
  kIMGCI_T1,
  kIMGDI_D1,
  kIMGI_D1,
  kIMGI_T1,
  kIMGO,
  kIMGO_E1,
  kIMGO_E2,
  kIMGO_E3,
  kIMGO_PROCESS,
  kISPINFO,
  kJPG,
  kLMI,
  kLSC,
  kLSC_IN,
  kLSC_OUT,
  kLSC_OUTINFO,
  kLTM_OUT,
  kLTMSO,
  kMEI_L0,
  kMEI_L0_P,
  kMEI_L1,
  kMEI_L1_P,
  kMETA_P1,
  kMETA_P2,
  kMIL,
  kMMAP_DS0_X,
  kMMAP_DS0_Y,
  kMMAP_DS1_X,
  kMMAP_DS1_Y,
  kMMAP_DS2_X,
  kMMAP_DS2_Y,
  kMMAP_X,
  kMMAP_Y,
  kMV_L0,
  kMV_L0_M0,
  kMV_L0_M1_P,
  kMV_L0_M2_P,
  kMV_L1,
  kMV_L1_M0_P,
  kMV_L1_M2_P,
  kMV_PACK,
  kMV_PACK_M0,
  kMV_PACK_M0_P,
  kMV_PACK_M1_P,
  kMV_PACK_M2_P,
  kN3D_INIT_INFO,
  kN3D_LOG,
  kN3D_NVRAM_IN,
  kN3D_NVRAM_OUT,
  kN3D_PROC_INFO,
  kP1_DEPTH,
  kP1_FE,
  kPIMGBI_P1,
  kPIMGCI_P1,
  kPIMGI_P1,
  kPOST_SW,
  kPS_MAP_X,
  kPS_MAP_Y,
  kRAWI_R2,
  kRECBI_D1,
  kRECBI_D2,
  kRECI_D1,
  kRECI_D2,
  kREG_DHZE,
  kREG_DIP,
  kREG_LTRAW,
  kREG_ME,
  kREG_P1,
  kREG_PQDIP_A,
  kREG_PQDIP_B,
  kREG_TRAW,
  kREG_WPE,
  kREG_WPEC,
  kREG_WPET,
  kREG_XTRAW,
  kRZH1N2TBO_R1,
  kRZH1N2TBO_R3,
  kRZH1N2TO_R1,
  kRZH1N2TO_R2,
  kRZH1N2TO_R3,
  kSHAD_CAL_INFO,
  kSKIP,
  kSNR_FACE_INFO,
  kSTEREO_TUNING,
  kSTT_PACK,
  kSTT_PACK_M0,
  kSWME_CONF_MAP,
  kSWME_GMV_IN,
  kSWME_IN,
  kSWME_IN_BASE,
  kSWME_IN_REF,
  kSWME_OUT,
  kSWME_PARA_BIN,
  kSWME_PARAM,
  kSWME_TUNING,
  kSWME_WPE_X_MAP,
  kSWME_WPE_Y_MAP,
  kSWME_WPEX_MAP,
  kSWME_WPEY_MAP,
  kTCCSI_P1,
  kTCCSO_P1,
  kTIMGO,
  kTIMGO_T1,
  kTNC_OUT,
  kTNCBO_D1,
  kTNCO_D1,
  kTNCSBO_D1,
  kTNCSBO_T1,
  kTNCSHO_D1,
  kTNCSHO_T1,
  kTNCSO_D1,
  kTNCSO_T1,
  kTNCSYO_D1,
  kTNCSYO_R1,
  kTNCSYO_T1,
  kTNRCI,
  kTNRLI,
  kTNRMI,
  kTNRMO,
  kTNRSI,
  kTNRSO,
  kTNRVBI,
  kTNRWI,
  kTNRWO,
  kTSFDBG_R1,
  kTSFDBG_R2,
  kTSFSO_R1,
  kTSFSO_R2,
  kUFDI_T1,
  kUNPACKCHANNEL,
  kVIPBI,
  kVIPI,
  kWARP_RSZ_X_IN,
  kWARP_RSZ_X_OUT,
  kWARP_RSZ_Y_IN,
  kWARP_RSZ_Y_OUT,
  kWDMAO,
  kWPE_MAP_RZ_X_IN,
  kWPE_MAP_RZ_X_OUT,
  kWPE_MAP_RZ_Y_IN,
  kWPE_MAP_RZ_Y_OUT,
  kWPE_MAP_X,
  kWPE_MAP_Y,
  kWPE_MASK,
  kWPEC_MAP_X,
  kWPEC_MAP_Y,
  kWPEC_MASK,
  kWPECI,
  kWPECO,
  kWPEI,
  kWPEO,
  kWPET_MAP_X,
  kWPET_MAP_Y,
  kWPET_MASK,
  kWPETI,
  kWPETO,
  kWROTO,
  kXTFDBO,
  kXTFDO,
  kXTMEO,
  kYUVBO_R1,
  kYUVBO_R2,
  kYUVBO_R3,
  kYUVBO_R4,
  kYUVBO_R5,
  kYUVBO_T1,
  kYUVBO_T2,
  kYUVBO_T3,
  kYUVBO_T4,
  kYUVCO_R1,
  kYUVO_R1,
  kYUVO_R2,
  kYUVO_R3,
  kYUVO_R4,
  kYUVO_R5,
  kYUVO_T1,
  kYUVO_T2,
  kYUVO_T3,
  kYUVO_T4,
  kYUVO_T5,
  kFWTNC_DHZ_GTM_STR_TBL,
  kFWTNC_DHZ_GTM_FACE_PARA,
  kFSC_OUT,
  kVAINR_AUXI_IN_DATA,
  kVAINR_AUXI_OUT_DATA,
  kVAINR_PROC_IN_AUXI,
  kVAINR_PROC_IN_FRC,
  kVAINR_PROC_IN_CURRENT_G,
  kVAINR_PROC_IN_CURRENT_R,
  kVAINR_PROC_IN_CURRENT_B,
  kVAINR_PROC_IN_PREVIOUS_G,
  kVAINR_PROC_IN_PREVIOUS_RB,
  kVAINR_PROC_OUT_FRC,
  kVAINR_PROC_OUT_RNN_G,
  kVAINR_PROC_OUT_RNN_RB,
  kVAINR_PROC_OUT_ISP_G,
  kVAINR_PROC_OUT_ISP_R,
  kVAINR_PROC_OUT_ISP_B,
  kVAINR_APU_NVRAM,
  kVAINR_SYS_NVRAM,
  kVAINR_WRK_MDLA_G,
  kVAINR_WRK_MDLA_RBA,
  kVAINR_WRK_IN_FRC,
  kVAINR_WRK_OUT_FRC,
  kVAINR_WRK_ALPHA,
  kVAINR_WRK_RESIDUAL,
  kVAINR_PARAM_INITINFO,
  kVAINR_PARAM_WRKBUFINFO,
  kVAINR_PARAM_DETAILEXTBUFINFO,
  kVAINR_PARAM_AUXIINPUT,
  kVAINR_PARAM_AUXIOUTPUT,
  kVAINR_PARAM_PROCESSINPUT,
  kVAINR_PARAM_PROCESSOUTPUT,
  kVAINR_PARAM_WPEQUERYIN,
  kVAINR_PARAM_WPEROIINFO,
  kVAINR_PARAM_WRK_MDLA_G,
  kVAINR_PARAM_WRK_MDLA_RBA,
  kVAINR_PARAM_WRK_IN_FRC,
  kVAINR_PARAM_WRK_OUT_FRC,
  kVAINR_PARAM_WRK_ALPHA,
  kVAINR_PARAM_WRK_RESIDUAL,
};

enum class eCategory {
  kCAPTURE,
  kSTREAMING,
};

enum class eSensorId {
  kINVALID = -1,
  kMAIN = 0,
  kSUB,
  kMAIN2,
  kSUB2,
  kMAIN3,
  kSUB3,
  kMAIN4,
  kSUB4,
  kMAIN5,
  kSUB5,
  kMAIN6,
  kSUB6,
};

enum class eSensorFeatureMode {
  kINVALID = -1,
  kOFF = 0,
  kMHDR,
  kMS_2EXP_SE_NE,
  kMS_2EXP_NE_SE,
  kSTG_2EXP_NE_SE,
  kSTG_3EXP_NE_ME_SE,
  kRCFG_1EXP_NE,
  kDCG_2EXP_DCG12,
  kDCG_2EXP_DCG14,
  kDCG_2EXP_HCG_LCG,
  kDCG_3EXP_DCG12_SGE,
  kDCG_3EXP_DCG14_SGE,
  kDCG_3EXP_SGE_DCG12,
  kDCG_3EXP_SGE_DCG14,
  kDCG_3EXP_HCG_LCG_SGE,
  kDCG_3EXP_SGE_HCG_LCG,
  kFC_2EXP_QUAD,
  kFC_3EXP_QUAD,
  kFMTFC_2EXP_NE_SE,
  kFMTFC_3EXP_NE_ME_SE,
  kQDOL4_4EXP_MQD12_MQD12,
  kQDOL4_4EXP_MQD14_MQD14,
  kQDOL4_3EXP_NE_MQD12,
  kQDOL4_3EXP_NE_MQD14,
  kQDOL4_3EXP_MQD12_SE,
  kQDOL4_3EXP_MQD14_SE,
  kFC_2EXP_MQD12,
  kFC_2EXP_MQD14,
};

enum class eSensorExp {
  kINVALID = -1,
  kNOREXP = 0,
  kSHTEXP,
  kMIDEXP,
  kNOREXP_SHTEXP,
  kNOREXP_MIDEXP_SHTEXP,
  kMIDEXP_SHTEXP,
};

enum class eExpOdr {
  kINVALID = -1,
  kE1 = 0,
  kE2,
  kE3,
  kE1_E2,
  kE2_E3,
  kE1_E2_E3,
};

enum class eDualCamId {
  kINVALID = -1,
  kMASTER = 0,
  kSLAVE,
};

struct NddData {
  int platform;        // No need, information from hal metadata
  int timestamp;       // No need, information from hal metadata
  int requestNo;       // No need, information from hal metadata
  int frameNo;         // No need, information from hal metadata
  eSensorId sensorId;  // Must
  int stage;           // Must
  int feature;         // No need, information from hal metadata
  int action;
  eSensorFeatureMode hdrMode;
  // Other {Sensor HDR Mode} includes:
  // mHDR //sensor merged with 10-bit out
  // ms_2exp_se_ne //m-stream with SE first
  // ms_2exp_ne_se //m-stream with NE first
  // stg_2exp_ne_se //stagger 2-exposure
  // stg_3exp_ne_me_se //stagger 3-exposure
  // rcfg_1exp_ne //reconfig 1 exposure
  // dcg_2exp_dcg12 //dcg 2-exp sensor merged 12-bit
  // dcg_2exp_dcg14 //dcg 2-exp sensor merged 14-bit
  // dcg_2exp_hcg_lcg //dcg 2-exp: high-conversion-gain and low-convergion-gain
  // dcg_3exp_dcg12_sge //dcg 3-exp: sensor merged 12-bit and single-exposure
  // dcg_3exp_dcg14_sge //dcg 3-exp: sensor merged 14-bit and single-exposure
  // dcg_3exp_sge_dcg12 //dcg 3-exp: single-exposure and sensor merged 12-bit
  // dcg_3exp_sge_dcg14 //dcg 3-exp: single-exposure and sensor merged 14-bit
  // dcg_3exp_hcg_lcg_sge //dcg 3-exp: high-conversion-gain,
  // low-convergion-gain, and single-exposure dcg_3exp_sge_hcg_lcg //dcg 3-exp:
  // single-exposure, high-conversion-gain, and low-conversion-gain fc_2exp_quad
  // //four-cell 2-exposure fc_3exp_quad //four-cell 3-exposure fmtfc_2exp_ne_se
  // //formatted-four-cell 2-exposure fmtfc_3exp_ne_me_se //formatted-four-cell
  // 3-exposure qdol4_4exp_mqd12_mqd12 //qdol4: 4-exposure, sensor merged 12-bit
  // and sensor merged 12-bit qdol4_4exp_mqd14_mqd14 //qdol4: 4-exposure, sensor
  // merged 14-bit and sensor merged 14-bit qdol4_3exp_ne_mqd12 //qdol4:
  // 3-exposure, normal exposure and sensor merged 12-bit qdol4_3exp_ne_mqd14
  // //qdol4: 3-exposure, normal exposure and sensor merged 14-bit
  // qdol4_3exp_mqd12_se //qdol4: 3-exposure, sensor merged 12-bit and short
  // exposure qdol4_3exp_mqd14_se //qdol4: 3-exposure, sensor merged 14-bit and
  // short exposure fc_2exp_mqd12 //four-cell: 2-exposure, sensor merged 12-bit
  // fc_2exp_mqd14 //four-cell: 2-exposure, sensor merged 14-bit
  string userstring;
  int pixelWidth;    // No need, information from ImageBuffer
  int pixelHeight;   // No need, information from ImageBuffer
  int byteWidth;     // No need, information from ImageBuffer
  int width;         // No need, information from ImageBuffer
  int height;        // No need, information from ImageBuffer
  int bitResultion;  // No need, information from ImageBuffer
  int bayerOrder;    // No need, information from ImageBuffer
  int signedness;    // No need, hardcode to 's0'
  int cell;
  int delay;
  int layer;
  eSensorExp sensorExp;
  eExpOdr expOdr;
  eDualCamId dualCamId;
  int version;

  NddData()
      : platform(-1),
        timestamp(-1),
        requestNo(-1),
        frameNo(-1),
        sensorId(eSensorId::kINVALID),
        stage(-1),
        feature(-1),
        action(-1),
        hdrMode(eSensorFeatureMode::kINVALID),
        userstring(""),
        pixelWidth(-1),
        pixelHeight(-1),
        byteWidth(-1),
        width(-1),
        height(-1),
        bitResultion(-1),
        bayerOrder(-1),
        signedness(-1),
        cell(-1),
        delay(-1),
        layer(-1),
        sensorExp(eSensorExp::kINVALID),
        expOdr(eExpOdr::kINVALID),
        dualCamId(eDualCamId::kINVALID),
        version(-1) {}
};

}  // namespace TuningUtils
}  // namespace NSCam

#endif  // INCLUDE_MTKCAM_INTERFACES_UTILS_NDD_NDD_AUTOGEN_DEF_H_
