/*
 * Copyright (C) 2022 MediaTek Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

/******************************************************************************
 *
 ******************************************************************************/
#include "../dbg_exif_def.h"

namespace dbg_cam_n3d_param_3 {
/******************************************************************************
 *
 ******************************************************************************/
enum
{
    //BEGIN_OF_EXIF_TAG
    N3D_AE_TAG_DEBUG_VERSION = 0,
    N3D_AE_SYNCNUM,
    N3D_AE_SYNCMODE,
    N3D_AE_SYNCPOLICY,
    N3D_AE_LOWER_BV,
    N3D_AE_UPPER_BV,
    N3D_AE_MASTER_IDX,

    N3D_AE_CAL_GAIN_R,
    N3D_AE_CAL_GAIN_G,
    N3D_AE_CAL_GAIN_B,
    N3D_AE_CAL_YGAIN,
    N3D_AE_CAL_OFFSET,
    N3D_AE_REG_OFFSET,

    N3D_AE_0_AEIDX,
    N3D_AE_0_AFEGAIN,
    N3D_AE_0_SHUTTER,
    N3D_AE_0_ISPGAIN,
    N3D_AE_0_CWY,
    N3D_AE_0_SYNCGAIN,

    N3D_AE_1_AEIDX,
    N3D_AE_1_AFEGAIN,
    N3D_AE_1_SHUTTER,
    N3D_AE_1_ISPGAIN,
    N3D_AE_1_CWY,
    N3D_AE_1_SYNCGAIN,

    //Intermedium Data
    N3D_AWB_TAG_DEBUG_VERSION,
    N3D_AWB_ADV_PP_LU_X,
    N3D_AWB_ADV_PP_LU_Y,
    N3D_AWB_ADV_PP_RD_X,
    N3D_AWB_ADV_PP_RD_Y,

    N3D_AWB_ADV_PP_APPLY_WB_R,
    N3D_AWB_ADV_PP_APPLY_WB_G,
    N3D_AWB_ADV_PP_APPLY_WB_B,

    N3D_AWB_ADV_PP_INVCCM_SUCCESS,

    N3D_AWB_ADV_PP_MAIN_CCM0,
    N3D_AWB_ADV_PP_MAIN_CCM1,
    N3D_AWB_ADV_PP_MAIN_CCM2,

    N3D_AWB_ADV_PP_MAIN_CCM3,
    N3D_AWB_ADV_PP_MAIN_CCM4,
    N3D_AWB_ADV_PP_MAIN_CCM5,

    N3D_AWB_ADV_PP_MAIN_CCM6,
    N3D_AWB_ADV_PP_MAIN_CCM7,
    N3D_AWB_ADV_PP_MAIN_CCM8,

    N3D_AWB_ADV_PP_SUB_CCM0,
    N3D_AWB_ADV_PP_SUB_CCM1,
    N3D_AWB_ADV_PP_SUB_CCM2,

    N3D_AWB_ADV_PP_SUB_CCM3,
    N3D_AWB_ADV_PP_SUB_CCM4,
    N3D_AWB_ADV_PP_SUB_CCM5,

    N3D_AWB_ADV_PP_SUB_CCM6,
    N3D_AWB_ADV_PP_SUB_CCM7,
    N3D_AWB_ADV_PP_SUB_CCM8,

    N3D_AWB_ADV_PP_MAIN_INV_CCM0 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM1 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM2 ,

    N3D_AWB_ADV_PP_MAIN_INV_CCM3 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM4 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM5 ,

    N3D_AWB_ADV_PP_MAIN_INV_CCM6 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM7 ,
    N3D_AWB_ADV_PP_MAIN_INV_CCM8 ,

    N3D_AWB_ADV_PP_MAIN_CCM_R,
    N3D_AWB_ADV_PP_MAIN_CCM_G,
    N3D_AWB_ADV_PP_MAIN_CCM_B,

    N3D_AWB_ADV_PP_SUB_CCM_TARGET_R,
    N3D_AWB_ADV_PP_SUB_CCM_TARGET_G,
    N3D_AWB_ADV_PP_SUB_CCM_TARGET_B,

    N3D_AWB_ADV_PP_SUB_WB_TARGET_R,
    N3D_AWB_ADV_PP_SUB_WB_TARGET_G,
    N3D_AWB_ADV_PP_SUB_WB_TARGET_B,

    N3D_AWB_ADV_PP_SUB_BEFORE_REFINE_R,
    N3D_AWB_ADV_PP_SUB_BEFORE_REFINE_G,
    N3D_AWB_ADV_PP_SUB_BEFORE_REFINE_B,

    N3D_AWB_ADV_PP_SUB_RESULT_RGAIN,
    N3D_AWB_ADV_PP_SUB_RESULT_GGAIN,
    N3D_AWB_ADV_PP_SUB_RESULT_BGAIN,

    N3D_AWB_ADV_PP_MAIN_VALID_BLK_COUNT,
    N3D_AWB_ADV_PP_MAIN_STAT_AVG_R,
    N3D_AWB_ADV_PP_MAIN_STAT_AVG_G,
    N3D_AWB_ADV_PP_MAIN_STAT_AVG_B,

    N3D_AWB_ADV_PP_SUB_VALID_BLK_COUNT,
    N3D_AWB_ADV_PP_SUB_STAT_AVG_R,
    N3D_AWB_ADV_PP_SUB_STAT_AVG_G,
    N3D_AWB_ADV_PP_SUB_STAT_AVG_B,

    N3D_AWB_MAIN_GAIN_DIFF_R,
    N3D_AWB_MAIN_GAIN_DIFF_G,
    N3D_AWB_MAIN_GAIN_DIFF_B,
    N3D_AWB_SUB_GAIN_DIFF_R,
    N3D_AWB_SUB_GAIN_DIFF_G,
    N3D_AWB_SUB_GAIN_DIFF_B,
    N3D_AWB_DO_OLD_ADVPP,

    N3D_AWB_BLEND_MAIN_STAT_AVG_R,
    N3D_AWB_BLEND_MAIN_STAT_AVG_G,
    N3D_AWB_BLEND_MAIN_STAT_AVG_B,
    N3D_AWB_BLEND_MAIN_COUNT,
    N3D_AWB_BLEND_MAIN_LIGHTMODE,

    N3D_AWB_BLEND_SUB_STAT_AVG_R,
    N3D_AWB_BLEND_SUB_STAT_AVG_G,
    N3D_AWB_BLEND_SUB_STAT_AVG_B,
    N3D_AWB_BLEND_SUB_COUNT,
    N3D_AWB_BLEND_SUB_LIGHTMODE,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_0,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_0,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_0,
    N3D_AWB_WP_SUB_R_0,
    N3D_AWB_WP_SUB_G_0,
    N3D_AWB_WP_SUB_B_0,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_1,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_1,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_1,
    N3D_AWB_WP_SUB_R_1,
    N3D_AWB_WP_SUB_G_1,
    N3D_AWB_WP_SUB_B_1,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_2,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_2,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_2,
    N3D_AWB_WP_SUB_R_2,
    N3D_AWB_WP_SUB_G_2,
    N3D_AWB_WP_SUB_B_2,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_3,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_3,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_3,
    N3D_AWB_WP_SUB_R_3,
    N3D_AWB_WP_SUB_G_3,
    N3D_AWB_WP_SUB_B_3,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_4,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_4,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_4,
    N3D_AWB_WP_SUB_R_4,
    N3D_AWB_WP_SUB_G_4,
    N3D_AWB_WP_SUB_B_4,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_5,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_5,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_5,
    N3D_AWB_WP_SUB_R_5,
    N3D_AWB_WP_SUB_G_5,
    N3D_AWB_WP_SUB_B_5,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_6,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_6,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_6,
    N3D_AWB_WP_SUB_R_6,
    N3D_AWB_WP_SUB_G_6,
    N3D_AWB_WP_SUB_B_6,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_7,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_7,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_7,
    N3D_AWB_WP_SUB_R_7,
    N3D_AWB_WP_SUB_G_7,
    N3D_AWB_WP_SUB_B_7,

    N3D_AWB_WP_MAIN_APPLY_WBGAIN_R_8,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_G_8,
    N3D_AWB_WP_MAIN_APPLY_WBGAIN_B_8,
    N3D_AWB_WP_SUB_R_8,
    N3D_AWB_WP_SUB_G_8,
    N3D_AWB_WP_SUB_B_8,

    N3D_AWB_DISPLAY_CAM,
    N3D_AWB_MAIN_CURR_GAIN_R,
    N3D_AWB_MAIN_CURR_GAIN_G,
    N3D_AWB_MAIN_CURR_GAIN_B,
    N3D_AWB_MAIN_CURR_CCT,


    N3D_AWB_MAIN_CURR_LIGHT_MODE,
    N3D_AWB_MAIN_CURR_LV,
    N3D_AWB_MAIN_CURR_TUNGSTEN_P,
    N3D_AWB_MAIN_CURR_WARM_FLUORESCENT_P,
    N3D_AWB_MAIN_CURR_FLUORESCENT_P,
    N3D_AWB_MAIN_CURR_CWF_P,
    N3D_AWB_MAIN_CURR_DAYLIGHT_P,
    N3D_AWB_MAIN_CURR_SHADE_P,
    N3D_AWB_MAIN_CURR_DAYLIGHT_FLUORESCENT_P,

    N3D_AWB_SUB_CURR_GAIN_R,
    N3D_AWB_SUB_CURR_GAIN_G,
    N3D_AWB_SUB_CURR_GAIN_B,
    N3D_AWB_SUB_CURR_CCT,


    N3D_AWB_SUB_CURR_LIGHT_MODE,
    N3D_AWB_SUB_CURR_LV,
    N3D_AWB_SUB_CURR_TUNGSTEN_P,
    N3D_AWB_SUB_CURR_WARM_FLUORESCENT_P,
    N3D_AWB_SUB_CURR_FLUORESCENT_P,
    N3D_AWB_SUB_CURR_CWF_P,
    N3D_AWB_SUB_CURR_DAYLIGHT_P,
    N3D_AWB_SUB_CURR_SHADE_P,
    N3D_AWB_SUB_CURR_DAYLIGHT_FLUORESCENT_P,


    // Output Variables
    N3D_AWB_SYNC_ADV_PP_ISFREERUN,
    N3D_AWB_SYNC_ADV_PP_GAIN_R,
    N3D_AWB_SYNC_ADV_PP_GAIN_G,
    N3D_AWB_SYNC_ADV_PP_GAIN_B,

    N3D_AWB_SYNC_BLENDING_ISFREERUN,
    N3D_AWB_SYNC_BLENDING_GAIN_R,
    N3D_AWB_SYNC_BLENDING_GAIN_G,
    N3D_AWB_SYNC_BLENDING_GAIN_B,

    N3D_AWB_SYNC_WP_GAIN_R,
    N3D_AWB_SYNC_WP_GAIN_G,
    N3D_AWB_SYNC_WP_GAIN_B,

    N3D_AWB_SYNC_FINAL_ISFREERUN,
    N3D_AWB_SYNC_FINAL_GAIN_R,
    N3D_AWB_SYNC_FINAL_GAIN_G,
    N3D_AWB_SYNC_FINAL_GAIN_B,

    N3D_AWB_SYNC_APPLYPREFER_GAIN_R,
    N3D_AWB_SYNC_APPLYPREFER_GAIN_G,
    N3D_AWB_SYNC_APPLYPREFER_GAIN_B,

    N3D_AWB_MAIN_OUTPUT_GAIN_R,
    N3D_AWB_MAIN_OUTPUT_GAIN_G,
    N3D_AWB_MAIN_OUTPUT_GAIN_B,
    N3D_AWB_MAIN_OUTPUT_CCT,

    N3D_AWB_SUB_OUTPUT_GAIN_R,
    N3D_AWB_SUB_OUTPUT_GAIN_G,
    N3D_AWB_SUB_OUTPUT_GAIN_B,
    N3D_AWB_SUB_OUTPUT_CCT,

    // Smooth temp variables
    N3D_AWB_PRE2_BUFF_GAIN_R,
    N3D_AWB_PRE2_BUFF_GAIN_G,
    N3D_AWB_PRE2_BUFF_GAIN_B,
    N3D_AWB_PRE_BUFF_GAIN_R,
    N3D_AWB_PRE_BUFF_GAIN_G,
    N3D_AWB_PRE_BUFF_GAIN_B,

    // Prefer temp variables
    N3D_AWB_RESULT_PREFER_TUNGSTEN_R,
    N3D_AWB_RESULT_PREFER_TUNGSTEN_G,
    N3D_AWB_RESULT_PREFER_TUNGSTEN_B,
    N3D_AWB_RESULT_PREFER_WARMFL_R,
    N3D_AWB_RESULT_PREFER_WARMFL_G,
    N3D_AWB_RESULT_PREFER_WARMFL_B,
    N3D_AWB_RESULT_PREFER_FL_R,
    N3D_AWB_RESULT_PREFER_FL_G,
    N3D_AWB_RESULT_PREFER_FL_B,
    N3D_AWB_RESULT_PREFER_CWF_R,
    N3D_AWB_RESULT_PREFER_CWF_G,
    N3D_AWB_RESULT_PREFER_CWF_B,
    N3D_AWB_RESULT_PREFER_DAY_R,
    N3D_AWB_RESULT_PREFER_DAY_G,
    N3D_AWB_RESULT_PREFER_DAY_B,
    N3D_AWB_RESULT_PREFER_SHADE_R,
    N3D_AWB_RESULT_PREFER_SHADE_G,
    N3D_AWB_RESULT_PREFER_SHADE_B,
    N3D_AWB_RESULT_PREFER_DAYFL_R,
    N3D_AWB_RESULT_PREFER_DAYFL_G,
    N3D_AWB_RESULT_PREFER_DAYFL_B,

    N3D_AWB_RESULT_BIAS_R,
    N3D_AWB_RESULT_BIAS_G,
    N3D_AWB_RESULT_BIAS_B,

    // Tuning Parameters
    N3D_AWB_TUNING_AWBSYNC_METHOD,

    N3D_AWB_TUNING_PP_CONSIDER_CCM,
    N3D_AWB_TUNING_PP_VALID_BLK_NUM_RATIO,
    N3D_AWB_TUNING_PP_AWBSTA_Y_TH_LOW,
    N3D_AWB_TUNING_PP_AWBSTA_Y_TH_HIGH,
    N3D_AWB_TUNING_PP_VALID_CHILBLK_TH,
    N3D_AWB_TUNING_PP_DIFF_TH,
    N3D_AWB_TUNING_PP_ENHANCE_CHANGE,

    N3D_AWB_TUNING_BLEND_TH0,
    N3D_AWB_TUNING_BLEND_TH1,
    N3D_AWB_TUNING_BLEND_TH2,
    N3D_AWB_TUNING_BLEND_TH3,

    N3D_AWB_TUNING_WP_AREA_HIT_RATIO,
    N3D_AWB_TUNING_WP_GB_RATIO_LOW_TH_MAIN,
    N3D_AWB_TUNING_WP_GB_RATIO_HIGH_TH_MAIN,
    N3D_AWB_TUNING_WP_GB_RATIO_LOW_TH_SUB,
    N3D_AWB_TUNING_WP_GB_RATIO_HIGH_TH_SUB,

    N3D_AWB_TUNING_WP_GR_RATIO_LOW_TH_MAIN,
    N3D_AWB_TUNING_WP_GR_RATIO_HIGH_TH_MAIN,
    N3D_AWB_TUNING_WP_GR_RATIO_LOW_TH_SUB,
    N3D_AWB_TUNING_WP_GR_RATIO_HIGH_TH_SUB,


    N3D_AWB_TUNING_WP_PP_GAIN_RATIO_TBL_X0,
    N3D_AWB_TUNING_WP_PP_GAIN_RATIO_TBL_X1,

    N3D_AWB_TUNING_WP_Y_LOW_TH,
    N3D_AWB_TUNING_WP_Y_HIGH_TH,

    N3D_AWB_SMOOTH_EN,
    N3D_AWB_SMOOTH_WEIGHT_PRE2,
    N3D_AWB_SMOOTH_WEIGHT_PRE,
    N3D_AWB_SMOOTH_WEIGHT_CURR,

    N3D_AWB_PREFER_TUNGSTEN_R,
    N3D_AWB_PREFER_TUNGSTEN_G,
    N3D_AWB_PREFER_TUNGSTEN_B,
    N3D_AWB_PREFER_WARMFL_R,
    N3D_AWB_PREFER_WARMFL_G,
    N3D_AWB_PREFER_WARMFL_B,
    N3D_AWB_PREFER_FL_R,
    N3D_AWB_PREFER_FL_G,
    N3D_AWB_PREFER_FL_B,
    N3D_AWB_PREFER_CWF_R,
    N3D_AWB_PREFER_CWF_G,
    N3D_AWB_PREFER_CWF_B,
    N3D_AWB_PREFER_DAY_R,
    N3D_AWB_PREFER_DAY_G,
    N3D_AWB_PREFER_DAY_B,
    N3D_AWB_PREFER_SHADE_R,
    N3D_AWB_PREFER_SHADE_G,
    N3D_AWB_PREFER_SHADE_B,
    N3D_AWB_PREFER_DAYFL_R,
    N3D_AWB_PREFER_DAYFL_G,
    N3D_AWB_PREFER_DAYFL_B,

    N3D_AWB_PREFER_LV_TH_L,
    N3D_AWB_PREFER_LV_TH_H,
    N3D_AWB_PREFER_TUNGSTEN_LV_R_L,
    N3D_AWB_PREFER_TUNGSTEN_LV_R_H,
    N3D_AWB_PREFER_TUNGSTEN_LV_G_L,
    N3D_AWB_PREFER_TUNGSTEN_LV_G_H,
    N3D_AWB_PREFER_TUNGSTEN_LV_B_L,
    N3D_AWB_PREFER_TUNGSTEN_LV_B_H,
    N3D_AWB_PREFER_WARMFL_LV_R_L,
    N3D_AWB_PREFER_WARMFL_LV_R_H,
    N3D_AWB_PREFER_WARMFL_LV_G_L,
    N3D_AWB_PREFER_WARMFL_LV_G_H,
    N3D_AWB_PREFER_WARMFL_LV_B_L,
    N3D_AWB_PREFER_WARMFL_LV_B_H,
    N3D_AWB_PREFER_FL_LV_R_L,
    N3D_AWB_PREFER_FL_LV_R_H,
    N3D_AWB_PREFER_FL_LV_G_L,
    N3D_AWB_PREFER_FL_LV_G_H,
    N3D_AWB_PREFER_FL_LV_B_L,
    N3D_AWB_PREFER_FL_LV_B_H,
    N3D_AWB_PREFER_CWF_LV_R_L,
    N3D_AWB_PREFER_CWF_LV_R_H,
    N3D_AWB_PREFER_CWF_LV_G_L,
    N3D_AWB_PREFER_CWF_LV_G_H,
    N3D_AWB_PREFER_CWF_LV_B_L,
    N3D_AWB_PREFER_CWF_LV_B_H,
    N3D_AWB_PREFER_DAY_LV_R_L,
    N3D_AWB_PREFER_DAY_LV_R_H,
    N3D_AWB_PREFER_DAY_LV_G_L,
    N3D_AWB_PREFER_DAY_LV_G_H,
    N3D_AWB_PREFER_DAY_LV_B_L,
    N3D_AWB_PREFER_DAY_LV_B_H,
    N3D_AWB_PREFER_SHADE_LV_R_L,
    N3D_AWB_PREFER_SHADE_LV_R_H,
    N3D_AWB_PREFER_SHADE_LV_G_L,
    N3D_AWB_PREFER_SHADE_LV_G_H,
    N3D_AWB_PREFER_SHADE_LV_B_L,
    N3D_AWB_PREFER_SHADE_LV_B_H,
    N3D_AWB_PREFER_DAYFL_LV_R_L,
    N3D_AWB_PREFER_DAYFL_LV_R_H,
    N3D_AWB_PREFER_DAYFL_LV_G_L,
    N3D_AWB_PREFER_DAYFL_LV_G_H,
    N3D_AWB_PREFER_DAYFL_LV_B_L,
    N3D_AWB_PREFER_DAYFL_LV_B_H,

    N3D_AWB_TAG_MAX
    //END_OF_EXIF_TAG
};

enum
{
    N3D_AE_TAG_MAX = N3D_AWB_TAG_DEBUG_VERSION
};


//N3D AE debug info
enum { N3D_AE_DEBUG_VERSION = 2 };
enum { N3D_AE_DEBUG_TAG_SIZE = (N3D_AE_TAG_MAX+10) };

typedef struct
{
    debug_exif_field Tag[N3D_AE_DEBUG_TAG_SIZE];
} N3D_AE_DEBUG_INFO_T;


/******************************************************************************
 *
 ******************************************************************************/

//N3D AWB debug info
enum { N3D_AWB_DEBUG_VERSION = 2 };
enum { N3D_AWB_DEBUG_TAG_SIZE = (N3D_AWB_TAG_MAX+10) };

typedef struct
{
    debug_exif_field Tag[N3D_AWB_DEBUG_TAG_SIZE];
} N3D_AWB_DEBUG_INFO_T;


/******************************************************************************
 *
 ******************************************************************************/
//Common Parameter Structure
typedef enum
{
    N3D_TAG_VERSION = 0,

}DEBUG_N3D_TAG_T;


// Native3D debug info
enum { N3D_DEBUG_TAG_SIZE = ((int)N3D_AE_DEBUG_TAG_SIZE+(int)N3D_AWB_DEBUG_TAG_SIZE) };
enum { N3D_DEBUG_TAG_VERSION = 3 };
enum { N3D_DEBUG_TAG_SUBVERSION = 0 };
#define N3D_DEBUG_TAG_VERSION_DP ((N3D_DEBUG_TAG_SUBVERSION << 16) | N3D_DEBUG_TAG_VERSION)

enum { DEBUG_N3D_AE_MODULE_ID   = 0x0001 };
enum { DEBUG_N3D_AWB_MODULE_ID  = 0x0002 };


typedef struct DEBUG_N3D_INFO_S
{
    debug_exif_field Tag[N3D_DEBUG_TAG_SIZE];
} DEBUG_N3D_INFO_T;


typedef struct
{
    N3D_AE_DEBUG_INFO_T  rAEDebugInfo;
    N3D_AWB_DEBUG_INFO_T rAWBDebugInfo;
} N3D_DEBUG_INFO_T;



/******************************************************************************
 *
 ******************************************************************************/
}  //namespace

