/*
 * Copyright (C) 2022 MediaTek Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef _MTK_CUSTOM_DEBUG_EXIF_CAM_DBG_CAM_MF_PARAM1_H_
#define _MTK_CUSTOM_DEBUG_EXIF_CAM_DBG_CAM_MF_PARAM1_H_
#pragma once

#include "../dbg_exif_def.h"

//
// Debug Exif Version 1 - MT6761
//
namespace dbg_cam_mf_param_1 {

 // MF debug info
enum { MF_DEBUG_TAG_VERSION = 1 };
enum { MF_DEBUG_TAG_SUBVERSION = 0 };
#define MF_DEBUG_TAG_VERSION_DP ((MF_DEBUG_TAG_SUBVERSION << 16) | MF_DEBUG_TAG_VERSION)

//MF Parameter Structure
typedef enum
{
    // ------------------------------------------------------------------------
    // MFNR SW related info
    // {{{
    //BEGIN_OF_EXIF_TAG
    MF_TAG_VERSION = 0,             //sw info
    MF_TAG_MFB_MODE,
    MF_TAG_MAX_FRAME_NUMBER,
    MF_TAG_PROCESSING_NUMBER,
    MF_TAG_EXPOSURE,
    MF_TAG_ISO,
    MF_TAG_ISO_HI_TH,
    MF_TAG_ISO_LOW_TH,
    MF_TAG_RAW_WIDTH,
    MF_TAG_RAW_HEIGHT,
    MF_TAG_BSS_ENABLE,
    MF_TAG_BSS_ROI_WIDTH,
    MF_TAG_BSS_ROI_HEIGHT,
    MF_TAG_BSS_SCALE_FACTOR,
    MF_TAG_BSS_CLIP_TH0,
    MF_TAG_BSS_CLIP_TH1,
    MF_TAG_BSS_INPUT0,
    MF_TAG_BSS_INPUT1,
    MF_TAG_BSS_INPUT2,
    MF_TAG_BSS_INPUT3,
    MF_TAG_BSS_INPUT4,
    MF_TAG_BSS_INPUT5,
    MF_TAG_MEMC_WIDTH,
    MF_TAG_MEMC_HEIGHT,
    MF_TAG_MEMC_INPUT_FORMAT,
    MF_TAG_MEMC_OUTPUT_FORMAT,
    MF_TAG_MEMC_SKIP,
    MF_TAG_MEMC_BAD_MB_COUNT0,
    MF_TAG_MEMC_BAD_MB_COUNT1,
    MF_TAG_MEMC_BAD_MB_COUNT2,
    MF_TAG_MEMC_BAD_MB_COUNT3,
    MF_TAG_MEMC_BAD_MB_COUNT4,
    MF_TAG_MEMC_BAD_MB_TH,
    MF_TAG_MEMC_BAD_MV_RANGE,
    MF_TAG_AIS_EXPOSURE,
    MF_TAG_AIS_ISO,
    MF_TAG_AIS_CALCULATED_EXPOSURE,
    MF_TAG_AIS_CALCULATED_ISO,
    MF_TAG_AIS_EXPOSURE_TH0,
    MF_TAG_AIS_ISO_TH0,
    MF_TAG_AIS_EXPOSURE_TH1,
    MF_TAG_AIS_ADVANCED_ENABLE,
    MF_TAG_AIS_ADVANCED_MAX_EXPOSURE,
    MF_TAG_AIS_ADVANCED_MAX_ISO,
    /* ANR (Stage: BASE) */
    MF_TAG_BASE_CAM_ANR_CON1,
    MF_TAG_BASE_CAM_ANR_CON2,
    MF_TAG_BASE_CAM_ANR_YAD1,
    MF_TAG_BASE_CAM_ANR_YAD2,
    MF_TAG_BASE_CAM_ANR_Y4LUT1,
    MF_TAG_BASE_CAM_ANR_Y4LUT2,
    MF_TAG_BASE_CAM_ANR_Y4LUT3,
    MF_TAG_BASE_CAM_ANR_C4LUT1,
    MF_TAG_BASE_CAM_ANR_C4LUT2,
    MF_TAG_BASE_CAM_ANR_C4LUT3,
    MF_TAG_BASE_CAM_ANR_A4LUT2,
    MF_TAG_BASE_CAM_ANR_A4LUT3,
    MF_TAG_BASE_CAM_ANR_L4LUT1,
    MF_TAG_BASE_CAM_ANR_L4LUT2,
    MF_TAG_BASE_CAM_ANR_L4LUT3,
    MF_TAG_BASE_CAM_ANR_PTY,
    MF_TAG_BASE_CAM_ANR_CAD,
    MF_TAG_BASE_CAM_ANR_PTC,
    MF_TAG_BASE_CAM_ANR_LCE,
    MF_TAG_BASE_CAM_ANR_MED1,
    MF_TAG_BASE_CAM_ANR_MED2,
    MF_TAG_BASE_CAM_ANR_MED3,
    MF_TAG_BASE_CAM_ANR_MED4,
    MF_TAG_BASE_CAM_ANR_HP1,
    MF_TAG_BASE_CAM_ANR_HP2,
    MF_TAG_BASE_CAM_ANR_HP3,
    MF_TAG_BASE_CAM_ANR_ACT1,
    MF_TAG_BASE_CAM_ANR_ACT2,
    MF_TAG_BASE_CAM_ANR_ACT3,
    MF_TAG_BASE_CAM_ANR_ACTY,
    MF_TAG_BASE_CAM_ANR_ACTC,
    MF_TAG_BASE_CAM_ANR2_CON1,
    MF_TAG_BASE_CAM_ANR2_CON2,
    MF_TAG_BASE_CAM_ANR2_YAD1,
    MF_TAG_BASE_CAM_ANR2_Y4LUT1,
    MF_TAG_BASE_CAM_ANR2_Y4LUT2,
    MF_TAG_BASE_CAM_ANR2_Y4LUT3,
    MF_TAG_BASE_CAM_ANR2_L4LUT1,
    MF_TAG_BASE_CAM_ANR2_L4LUT2,
    MF_TAG_BASE_CAM_ANR2_L4LUT3,
    MF_TAG_BASE_CAM_ANR2_CAD,
    MF_TAG_BASE_CAM_ANR2_PTC,
    MF_TAG_BASE_CAM_ANR2_LCE,
    MF_TAG_BASE_CAM_ANR2_MED1,
    MF_TAG_BASE_CAM_ANR2_MED2,
    MF_TAG_BASE_CAM_ANR2_MED3,
    MF_TAG_BASE_CAM_ANR2_MED4,
    MF_TAG_BASE_CAM_ANR2_ACTY,
    MF_TAG_BASE_CAM_ANR2_ACTC,
    /* ANR (Stage: BEFORE_MFB) */
    MF_TAG_BEFORE_MFB_CAM_ANR_CON1,
    MF_TAG_BEFORE_MFB_CAM_ANR_CON2,
    MF_TAG_BEFORE_MFB_CAM_ANR_YAD1,
    MF_TAG_BEFORE_MFB_CAM_ANR_YAD2,
    MF_TAG_BEFORE_MFB_CAM_ANR_Y4LUT1,
    MF_TAG_BEFORE_MFB_CAM_ANR_Y4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR_Y4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR_C4LUT1,
    MF_TAG_BEFORE_MFB_CAM_ANR_C4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR_C4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR_A4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR_A4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR_L4LUT1,
    MF_TAG_BEFORE_MFB_CAM_ANR_L4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR_L4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR_PTY,
    MF_TAG_BEFORE_MFB_CAM_ANR_CAD,
    MF_TAG_BEFORE_MFB_CAM_ANR_PTC,
    MF_TAG_BEFORE_MFB_CAM_ANR_LCE,
    MF_TAG_BEFORE_MFB_CAM_ANR_MED1,
    MF_TAG_BEFORE_MFB_CAM_ANR_MED2,
    MF_TAG_BEFORE_MFB_CAM_ANR_MED3,
    MF_TAG_BEFORE_MFB_CAM_ANR_MED4,
    MF_TAG_BEFORE_MFB_CAM_ANR_HP1,
    MF_TAG_BEFORE_MFB_CAM_ANR_HP2,
    MF_TAG_BEFORE_MFB_CAM_ANR_HP3,
    MF_TAG_BEFORE_MFB_CAM_ANR_ACT1,
    MF_TAG_BEFORE_MFB_CAM_ANR_ACT2,
    MF_TAG_BEFORE_MFB_CAM_ANR_ACT3,
    MF_TAG_BEFORE_MFB_CAM_ANR_ACTY,
    MF_TAG_BEFORE_MFB_CAM_ANR_ACTC,
    MF_TAG_BEFORE_MFB_CAM_ANR2_CON1,
    MF_TAG_BEFORE_MFB_CAM_ANR2_CON2,
    MF_TAG_BEFORE_MFB_CAM_ANR2_YAD1,
    MF_TAG_BEFORE_MFB_CAM_ANR2_Y4LUT1,
    MF_TAG_BEFORE_MFB_CAM_ANR2_Y4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR2_Y4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR2_L4LUT1,
    MF_TAG_BEFORE_MFB_CAM_ANR2_L4LUT2,
    MF_TAG_BEFORE_MFB_CAM_ANR2_L4LUT3,
    MF_TAG_BEFORE_MFB_CAM_ANR2_CAD,
    MF_TAG_BEFORE_MFB_CAM_ANR2_PTC,
    MF_TAG_BEFORE_MFB_CAM_ANR2_LCE,
    MF_TAG_BEFORE_MFB_CAM_ANR2_MED1,
    MF_TAG_BEFORE_MFB_CAM_ANR2_MED2,
    MF_TAG_BEFORE_MFB_CAM_ANR2_MED3,
    MF_TAG_BEFORE_MFB_CAM_ANR2_MED4,
    MF_TAG_BEFORE_MFB_CAM_ANR2_ACTY,
    MF_TAG_BEFORE_MFB_CAM_ANR2_ACTC,
    /* ANR (Stage: AFTER_MFB) */
    MF_TAG_AFTER_MFB_CAM_ANR_CON1,
    MF_TAG_AFTER_MFB_CAM_ANR_CON2,
    MF_TAG_AFTER_MFB_CAM_ANR_YAD1,
    MF_TAG_AFTER_MFB_CAM_ANR_YAD2,
    MF_TAG_AFTER_MFB_CAM_ANR_Y4LUT1,
    MF_TAG_AFTER_MFB_CAM_ANR_Y4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR_Y4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR_C4LUT1,
    MF_TAG_AFTER_MFB_CAM_ANR_C4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR_C4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR_A4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR_A4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR_L4LUT1,
    MF_TAG_AFTER_MFB_CAM_ANR_L4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR_L4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR_PTY,
    MF_TAG_AFTER_MFB_CAM_ANR_CAD,
    MF_TAG_AFTER_MFB_CAM_ANR_PTC,
    MF_TAG_AFTER_MFB_CAM_ANR_LCE,
    MF_TAG_AFTER_MFB_CAM_ANR_MED1,
    MF_TAG_AFTER_MFB_CAM_ANR_MED2,
    MF_TAG_AFTER_MFB_CAM_ANR_MED3,
    MF_TAG_AFTER_MFB_CAM_ANR_MED4,
    MF_TAG_AFTER_MFB_CAM_ANR_HP1,
    MF_TAG_AFTER_MFB_CAM_ANR_HP2,
    MF_TAG_AFTER_MFB_CAM_ANR_HP3,
    MF_TAG_AFTER_MFB_CAM_ANR_ACT1,
    MF_TAG_AFTER_MFB_CAM_ANR_ACT2,
    MF_TAG_AFTER_MFB_CAM_ANR_ACT3,
    MF_TAG_AFTER_MFB_CAM_ANR_ACTY,
    MF_TAG_AFTER_MFB_CAM_ANR_ACTC,
    MF_TAG_AFTER_MFB_CAM_ANR2_CON1,
    MF_TAG_AFTER_MFB_CAM_ANR2_CON2,
    MF_TAG_AFTER_MFB_CAM_ANR2_YAD1,
    MF_TAG_AFTER_MFB_CAM_ANR2_Y4LUT1,
    MF_TAG_AFTER_MFB_CAM_ANR2_Y4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR2_Y4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR2_L4LUT1,
    MF_TAG_AFTER_MFB_CAM_ANR2_L4LUT2,
    MF_TAG_AFTER_MFB_CAM_ANR2_L4LUT3,
    MF_TAG_AFTER_MFB_CAM_ANR2_CAD,
    MF_TAG_AFTER_MFB_CAM_ANR2_PTC,
    MF_TAG_AFTER_MFB_CAM_ANR2_LCE,
    MF_TAG_AFTER_MFB_CAM_ANR2_MED1,
    MF_TAG_AFTER_MFB_CAM_ANR2_MED2,
    MF_TAG_AFTER_MFB_CAM_ANR2_MED3,
    MF_TAG_AFTER_MFB_CAM_ANR2_MED4,
    MF_TAG_AFTER_MFB_CAM_ANR2_ACTY,
    MF_TAG_AFTER_MFB_CAM_ANR2_ACTC,
    /* EE (Stage: BASE) */
    MF_TAG_BASE_CAM_SEEE_SRK_CTRL,
    MF_TAG_BASE_CAM_SEEE_CLIP_CTRL,
    MF_TAG_BASE_CAM_SEEE_FLT_CTRL_1,
    MF_TAG_BASE_CAM_SEEE_FLT_CTRL_2,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_01,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_02,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_03,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_04,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_05,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_06,
    MF_TAG_BASE_CAM_SEEE_EDTR_CTRL,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_07,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_08,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_09,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_10,
    MF_TAG_BASE_CAM_SEEE_GLUT_CTRL_11,
    MF_TAG_BASE_CAM_SEEE_OUT_EDGE_CTRL,
    MF_TAG_BASE_CAM_SEEE_SE_Y_CTRL,
    MF_TAG_BASE_CAM_SEEE_SE_EDGE_CTRL_1,
    MF_TAG_BASE_CAM_SEEE_SE_EDGE_CTRL_2,
    MF_TAG_BASE_CAM_SEEE_SE_EDGE_CTRL_3,
    MF_TAG_BASE_CAM_SEEE_SE_SPECL_CTRL,
    MF_TAG_BASE_CAM_SEEE_SE_CORE_CTRL_1,
    MF_TAG_BASE_CAM_SEEE_SE_CORE_CTRL_2,
    /* EE (Stage: BEFORE_MFB) */
    MF_TAG_BEFORE_MFB_CAM_SEEE_SRK_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_CLIP_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_FLT_CTRL_1,
    MF_TAG_BEFORE_MFB_CAM_SEEE_FLT_CTRL_2,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_01,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_02,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_03,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_04,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_05,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_06,
    MF_TAG_BEFORE_MFB_CAM_SEEE_EDTR_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_07,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_08,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_09,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_10,
    MF_TAG_BEFORE_MFB_CAM_SEEE_GLUT_CTRL_11,
    MF_TAG_BEFORE_MFB_CAM_SEEE_OUT_EDGE_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_Y_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_EDGE_CTRL_1,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_EDGE_CTRL_2,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_EDGE_CTRL_3,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_SPECL_CTRL,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_CORE_CTRL_1,
    MF_TAG_BEFORE_MFB_CAM_SEEE_SE_CORE_CTRL_2,
    /* EE (Stage: AFTER_MFB) */
    MF_TAG_AFTER_MFB_CAM_SEEE_SRK_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_CLIP_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_FLT_CTRL_1,
    MF_TAG_AFTER_MFB_CAM_SEEE_FLT_CTRL_2,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_01,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_02,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_03,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_04,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_05,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_06,
    MF_TAG_AFTER_MFB_CAM_SEEE_EDTR_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_07,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_08,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_09,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_10,
    MF_TAG_AFTER_MFB_CAM_SEEE_GLUT_CTRL_11,
    MF_TAG_AFTER_MFB_CAM_SEEE_OUT_EDGE_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_Y_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_EDGE_CTRL_1,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_EDGE_CTRL_2,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_EDGE_CTRL_3,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_SPECL_CTRL,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_CORE_CTRL_1,
    MF_TAG_AFTER_MFB_CAM_SEEE_SE_CORE_CTRL_2,
    /* MFB (Stage: IN_MFB) */
    MF_TAG_IN_MFB_CAM_MFB_LL_CON2,
    MF_TAG_IN_MFB_CAM_MFB_LL_CON3,
    MF_TAG_IN_MFB_CAM_MFB_LL_CON4,
    MF_TAG_IN_MFB_CAM_MFB_LL_CON5,
    MF_TAG_IN_MFB_CAM_MFB_LL_CON6,

    /* MFB (Stage: AFTER_MFB) */
    MF_TAG_AFTER_MFB_CAM_MFB_LL_CON2,
    MF_TAG_AFTER_MFB_CAM_MFB_LL_CON3,
    MF_TAG_AFTER_MFB_CAM_MFB_LL_CON4,
    MF_TAG_AFTER_MFB_CAM_MFB_LL_CON5,
    MF_TAG_AFTER_MFB_CAM_MFB_LL_CON6,

    /* MIX (Stage: AFTER_MFB) */
    MF_TAG_AFTER_MFB_CAM_MIX3_CTRL_0,
    MF_TAG_AFTER_MFB_CAM_MIX3_CTRL_1,
    MF_TAG_AFTER_MFB_CAM_MIX3_SPARE,

    MF_TAG_BSS_REORDER_MAPPING_00                                             , // Frame Mapping: OriginOrder =
    MF_TAG_BSS_REORDER_MAPPING_01                                             , //                (FrameNumber % 10000) * 100
    MF_TAG_BSS_REORDER_MAPPING_02                                             , //                + NewOrder
    MF_TAG_BSS_REORDER_MAPPING_03                                             , // ex: FrameNumber 10189
    MF_TAG_BSS_REORDER_MAPPING_04                                             , //     OriginOrder 2
    MF_TAG_BSS_REORDER_MAPPING_05                                             , //     NewOrder    1
    MF_TAG_BSS_REORDER_MAPPING_06                                             , //     MF_TAG_BSS_REORDER_MAPPING_02 = 18901
    MF_TAG_BSS_REORDER_MAPPING_07                                             ,
    MF_TAG_BSS_ORDER_IDX                                                      ,

    //indicates to size
    MF_DEBUG_TAG_SIZE
    //END_OF_EXIF_TAG
} DEBUG_MF_TAG_T;

typedef struct DEBUG_MF_INFO_S
{
    debug_exif_field Tag[MF_DEBUG_TAG_SIZE];
} DEBUG_MF_INFO_T;


}  //namespace
#endif//_MTK_CUSTOM_DEBUG_EXIF_CAM_DBG_CAM_MF_PARAM10_H_
