/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * Copyright (C) 2023, Google Inc.
 *
 * lpnr.cpp - MtkISP7 ImgSys Low Pass Noise Reduction Tasks
 */

#include "lpnr.h"

#include <libcamera/control_ids.h>
#include <libcamera/formats.h>
#include <libcamera/request.h>

#include "libcamera/internal/task_scheduler.h"

#include "pipeline/mtkisp7/imgsys/imgsys.h"
#include "pipeline/mtkisp7/odt/on_device_tuner.h"

#include "single_device.h"

namespace libcamera {

LOG_DECLARE_CATEGORY(MtkISP7)

namespace {

static constexpr Size kTrawSttSize{ 738624, 1 };

} //namespace

int LpnrTasksManager::configure(const Size &bayerInputSize,
				const Size &yuvOutputSize1, const Size &yuvOutputSize2)
{
	yuvOutputSize1_ = yuvOutputSize1;
	yuvOutputSize2_ = yuvOutputSize2;
	bayerInputSize_ = bayerInputSize;

	lpnrSizes.resize(4);
	Size size = bayerInputSize_;

	/* Assign the size to 1/4 of the previous level.
	 * Align to 2 for hardware's requirement */
	for (size_t i = 0; i < lpnrSizes.size(); i++) {
		lpnrSizes[i] = size;
		size.width = (size.width + 3) / 4;
		size.height = (size.height + 3) / 4;
		size.alignUpTo(2, 2);
	}

	/* Allocate buffer pools */
	lpnrStt_.createBuffers(dmaHeap_, formats::MTFD_MTISP, kTrawSttSize, 5, DmaHeap::CMA);

	/* Level 0 uses NV12_10P_MTISP */
	lpnr_[0].setFormat(dmaHeap_, formats::NV12_10P_MTISP, lpnrSizes[0]);
	for (unsigned int i = 1; i < lpnr_.size(); i++) {
		lpnr_[i].setFormat(dmaHeap_, formats::NV12_12P_MTISP, lpnrSizes[i]);
	}

	lpnrStt_.mmap();

	return 0;
}

int LpnrTasksManager::releaseBuffers()
{
	lpnrStt_.release();
	for (unsigned int i = 1; i < lpnr_.size(); i++)
		lpnr_[i].release();

	return 0;
}

int LpnrTasksManager::start()
{
#if !V4L2_STANDARD_MODE
	for (auto &pool : allBufferPools_)
		imgSys_->handleIova(ImgSysDevice::Add, *pool);
#endif
	return 0;
}

int LpnrTasksManager::stop()
{
#if !V4L2_STANDARD_MODE
	for (auto &pool : allBufferPools_)
		imgSys_->handleIova(ImgSysDevice::Delete, *pool);
#endif
	return 0;
}

LpnrTasksManager::LpnrTasksManager(
	ImgSysDevice *imgSys, DmaHeap *dmaHeap, OnDeviceTuner *odt)
{
	imgSys_ = imgSys;
	dmaHeap_ = dmaHeap;
	onDeviceTuner_ = odt;
}

void LpnrTasksManager::makeLPNRFrames(LPNRFrames &lpnr,
				      SharedMailBox<InfoFrame> &p1Raw,
				      FrameBuffer *output1Frame,
				      FrameBuffer *output2Frame)
{
	lpnr.still1Output = output1Frame;
	lpnr.still2Output = output2Frame;

	/* Should be created and generated by IPA, once it's ready */
	SharedMailBox<InfoFrame> xtrTun = makeMailBox<InfoFrame>();
	std::vector<SharedMailBox<InfoFrame>> dipTun = makeMailBoxVector<InfoFrame>(4);

	SharedMailBox<InfoFrame> dipTunPq = makeMailBox<InfoFrame>();
	SharedMailBox<InfoFrame> dipTunY2YPq = makeMailBox<InfoFrame>();

	SharedMailBox<InfoFrame> xtrStt = makeMailBox<InfoFrame>();
	std::vector<SharedMailBox<InfoFrame>> dipImgi = makeMailBoxVector<InfoFrame>(4);

	SharedMailBox<bool> highIsoMode = makeMailBox<bool>();

	/* Frames used by XtrTask */
	XtrFrames &xtrFrames = lpnr.xtrFrames;
	xtrFrames.in.p1Raw = p1Raw;
	xtrFrames.in.xtrTun = xtrTun;
	xtrFrames.out.dipImgi = dipImgi;
	xtrFrames.out.xtrStt = xtrStt;

	/* Frames used by LpnrDipTask */
	LpnrDipFrames &lpnrDipFrames = lpnr.lpnrDipFrames;
	lpnrDipFrames.in.dipTunPq = dipTunPq;
	lpnrDipFrames.in.dipTunY2YPq = dipTunY2YPq;
	lpnrDipFrames.in.dipTun = dipTun;
	lpnrDipFrames.in.dipImgi = dipImgi;
	lpnrDipFrames.in.highIsoMode = highIsoMode;
}

std::tuple<XTRTask *, LpnrDipTask *>
LpnrTasksManager::makeLpnrTasks(LPNRFrames &lpnr, Scheduler *scheduler,
				const std::string &id, Request *request,
				uint32_t internalRequestId, ImgSysDevice *imgSys)
{
	XTRTask *xtrTask = new XTRTask(
			scheduler, id, request, internalRequestId, imgSys, lpnr, this);
	LpnrDipTask *dipTask = new LpnrDipTask(
			scheduler, id, request, internalRequestId, imgSys, lpnr, this);
	return std::make_tuple(xtrTask, dipTask);
}

using namespace NSCam::NSImgStream;

XTRTask::XTRTask(Scheduler *scheduler, const std::string &id,
		 Request *request, uint32_t internalRequestId,
		 ImgSysDevice *imgSys, LPNRFrames &lpnr, LpnrTasksManager *manager)
	: Task(scheduler, id), requestHelper_(this, request, imgSys),
	  request_(request), internalRequestId_(internalRequestId), manager_(manager)
{
	frames_ = lpnr.xtrFrames;
}

void XTRTask::allocateOutputBuffers()
{
	auto &out = frames_.out;

	/* Downscaled demosaic YUV frames */
	for (unsigned int i = 0; i < manager_->lpnr_.size(); i++)
		manager_->lpnr_[i].fetch(out.dipImgi[i]);

	/* Statistics */
	manager_->lpnrStt_.fetch(out.xtrStt);
}

void XTRTask::notifyDone()
{
	manager_->onDeviceTuner_->tuneXtr(internalRequestId_, frames_);
	Task::notifyDone();
}

void XTRTask::run()
{
	allocateOutputBuffers();

	auto &lpnrSizes = manager_->lpnrSizes;

	MUINT32 timestampMili = request_->metadata().get(controls::SensorTimestamp).value_or(0);
	SingleDeviceRequest sdRequest;

	sdRequest.init(internalRequestId_, timestampMili, "XTRTask");

	auto &in = frames_.in;
	auto &out = frames_.out;

	/* TR_R2Y */
	StageEx &TR_R2Y = sdRequest.emplaceStage(PEU_Stage::TR_R2Y);

	TR_R2Y.input(in.p1Raw->get(), IMG_PORT_TIMGI, 0, Size{ 0, 0 });
	TR_R2Y.input(in.xtrTun->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	TR_R2Y.output(out.dipImgi[0]->get(), IMG_PORT_TYUVO, 0, lpnrSizes[0]);
	TR_R2Y.output(out.dipImgi[1]->get(), IMG_PORT_TYUV2O, 1, lpnrSizes[0]);
	TR_R2Y.output(out.dipImgi[2]->get(), IMG_PORT_TYUV3O, 1, lpnrSizes[1]);
	TR_R2Y.output(out.dipImgi[3]->get(), IMG_PORT_TYUV4O, 1, lpnrSizes[2]);
	TR_R2Y.output(out.xtrStt->get(), IMG_PORT_IMGSTATO, 0, lpnrSizes[0]);

	requestHelper_.queueRequest(UserIdLpnr, sdRequest);
}

LpnrDipTask::LpnrDipTask(Scheduler *scheduler, const std::string &id,
			 Request *request, uint32_t internalRequestId,
			 ImgSysDevice *imgSys, LPNRFrames &lpnr, LpnrTasksManager *manager)
	: Task(scheduler, id), requestHelper_(this, request, imgSys),
	  request_(request), internalRequestId_(internalRequestId), manager_(manager)
{
	frames_ = lpnr.lpnrDipFrames;

	/* Intermediate frames */
	dipImg3o.resize(4);
	for (size_t i = 0; i < dipImg3o.size(); i++) {
		dipImg3o[i] = makeMailBox<InfoFrame>();
	}

	/* Reci use the output of img3o of the previous stage */
	reci.resize(3);
	for (int i = 0; i < 3; i++)
		reci[i] = dipImg3o[i + 1];

	stillOutput1_ = lpnr.still1Output;
	stillOutput2_ = lpnr.still2Output;
}

void LpnrDipTask::allocateOutputBuffers()
{
	/* allocate img3o (NR frame) for each stages */
	for (unsigned int i = 0; i < dipImg3o.size(); i++)
		manager_->lpnr_[i].fetch(dipImg3o[i]);
}

void LpnrDipTask::notifyDone()
{
	manager_->onDeviceTuner_->tuneLpnrDip(
		request_, internalRequestId_, frames_, reci, dipImg3o, stillOutput1_, stillOutput2_);
	Task::notifyDone();
}

void LpnrDipTask::run()
{
	allocateOutputBuffers();

	auto &lpnrSizes = manager_->lpnrSizes;
	MUINT32 timestampMili = request_->metadata().get(controls::SensorTimestamp).value_or(0);

	SingleDeviceRequest sdRequest;
	sdRequest.init(internalRequestId_, timestampMili, "LPNRTask");

	auto &in = frames_.in;

	/* P2_MS_F3 */
	StageEx &P2_MS_F3 = sdRequest.emplaceStage(PEU_Stage::P2_MS_F3);

	P2_MS_F3.input(in.dipImgi[3]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_MS_F3.input(in.dipTun[3]->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });
	P2_MS_F3.output(dipImg3o[3]->get(), IMG_PORT_IMG3O, 0, lpnrSizes[3]);
	P2_MS_F3.setMultiScale(IMG_MULTI_SCALE_DOWN4, 3, 4);

	/* P2_MS_F2 */
	StageEx &P2_MS_F2 = sdRequest.emplaceStage(PEU_Stage::P2_MS_F2);

	P2_MS_F2.input(in.dipImgi[2]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_MS_F2.input(reci[2]->get(), IMG_PORT_REC_DSI, 1, Size{ 0, 0 });
	P2_MS_F2.input(in.dipTun[2]->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	P2_MS_F2.output(dipImg3o[2]->get(), IMG_PORT_IMG3O, 0, lpnrSizes[2]);

	P2_MS_F2.setMultiScale(IMG_MULTI_SCALE_DOWN4, 2, 4);

	/* P2_MS_F1 */
	StageEx &P2_MS_F1 = sdRequest.emplaceStage(PEU_Stage::P2_MS_F1);

	P2_MS_F1.input(in.dipImgi[1]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_MS_F1.input(reci[1]->get(), IMG_PORT_REC_DSI, 1, Size{ 0, 0 });
	P2_MS_F1.input(in.dipTun[1]->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	P2_MS_F1.output(dipImg3o[1]->get(), IMG_PORT_IMG3O, 0, lpnrSizes[1]);

	P2_MS_F1.setMultiScale(IMG_MULTI_SCALE_DOWN4, 1, 4);

	if (in.highIsoMode->get())
		HighIsoStage(sdRequest);
	else
		LowIsoStages(sdRequest);

	requestHelper_.queueRequest(UserIdLpnr, sdRequest);
}

void LpnrDipTask::LowIsoStages(SingleDeviceRequest &sdRequest)
{
	auto &in = frames_.in;
	auto &lpnrSizes = manager_->lpnrSizes;

	/* P2_MS_F0_PQ_DIP */
	StageEx &P2_MS_F0_PQ_DIP = sdRequest.emplaceStage(PEU_Stage::P2_MS_F0_PQ_DIP);

	P2_MS_F0_PQ_DIP.input(in.dipImgi[0]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_MS_F0_PQ_DIP.input(reci[0]->get(), IMG_PORT_REC_DSI, 1, Size{ 0, 0 });
	P2_MS_F0_PQ_DIP.input(in.dipTunPq->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	P2_MS_F0_PQ_DIP.output(dipImg3o[0]->get(), IMG_PORT_IMG3O, 0, lpnrSizes[0]);

	if (stillOutput1_) {
		InfoFrame info(formats::NV12, manager_->yuvOutputSize1_, stillOutput1_, 64);
		Rectangle crop = ImgSysDevice::getCrop(lpnrSizes[0], info.size());
		// There is no noisy border issue in LPNR, but for consistency we do crop.
		crop = ImgSysDevice::cropNoisyBorder(crop);
		P2_MS_F0_PQ_DIP.output(info, IMG_PORT_WDMAO, 0, crop);
	}

	if (stillOutput2_) {
		InfoFrame info(formats::NV12, manager_->yuvOutputSize2_, stillOutput2_, 64);
		Rectangle crop = ImgSysDevice::getCrop(lpnrSizes[0], info.size());
		crop = ImgSysDevice::cropNoisyBorder(crop);
		P2_MS_F0_PQ_DIP.output(info, IMG_PORT_WROTO, 0, crop);
	}

	P2_MS_F0_PQ_DIP.setMultiScale(IMG_MULTI_SCALE_DOWN4, 0, 4);
	P2_MS_F0_PQ_DIP.setPqInfo();
}

void LpnrDipTask::HighIsoStage(SingleDeviceRequest &sdRequest)
{
	auto &in = frames_.in;
	auto &lpnrSizes = manager_->lpnrSizes;

	/* P2_MS_F0_H */
	StageEx &P2_MS_F0_H = sdRequest.emplaceStage(PEU_Stage::P2_MS_F0_H);

	P2_MS_F0_H.input(in.dipImgi[0]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_MS_F0_H.input(reci[0]->get(), IMG_PORT_REC_DSI, 1, Size{ 0, 0 });
	P2_MS_F0_H.input(in.dipTun[0]->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	P2_MS_F0_H.output(dipImg3o[0]->get(), IMG_PORT_IMG3O, 0, lpnrSizes[0]);

	P2_MS_F0_H.setMultiScale(IMG_MULTI_SCALE_DOWN4, 0, 4);

	/* P2_Y2Y_PQ_DIP */
	StageEx &P2_Y2Y_PQ_DIP = sdRequest.emplaceStage(PEU_Stage::P2_Y2Y_PQ_DIP);

	P2_Y2Y_PQ_DIP.input(dipImg3o[0]->get(), IMG_PORT_IMGI, 0, Size{ 0, 0 });
	P2_Y2Y_PQ_DIP.input(in.dipTunY2YPq->get(), IMG_PORT_METAI, 0, Size{ 0, 0 });

	if (stillOutput1_) {
		InfoFrame info(formats::NV12, manager_->yuvOutputSize1_, stillOutput1_, 64);
		Rectangle crop = ImgSysDevice::getCrop(lpnrSizes[0], info.size());
		crop = ImgSysDevice::cropNoisyBorder(crop);
		P2_Y2Y_PQ_DIP.output(info, IMG_PORT_WDMAO, 0, crop);
	}

	if (stillOutput2_) {
		InfoFrame info(formats::NV12, manager_->yuvOutputSize2_, stillOutput2_, 64);
		Rectangle crop = ImgSysDevice::getCrop(lpnrSizes[0], info.size());
		crop = ImgSysDevice::cropNoisyBorder(crop);
		P2_Y2Y_PQ_DIP.output(info, IMG_PORT_WROTO, 0, crop);
	}

	P2_Y2Y_PQ_DIP.setPqInfo();
}

} /* namespace libcamera */
