/*
 * Copyright (C) 2023, Google Inc.
 *
 * mcnr.h - MtkISP7 ImgSys Device Motion Compensation Noise Reduction
 */

#pragma once

#include "libcamera/internal/info_frame.h"
#include "libcamera/internal/task_scheduler.h"

#include "pipeline/mtkisp7/odt/on_device_tuner.h"

#include "imgsys.h"

namespace libcamera {

class Dip1Task;
class Dip2Task;
class MeATask;
class MeBTask;
class TrTask;
class MtkISP7CameraData;

struct MCNRPrevOutput {
	/* For the first frame, there is no previous outputs. valid = false
	 * indicates that contents are empty. */
	bool valid = false;

	/* Generated by the previous frame's MCNR processing with the
	 * corresponding names with the prefix "prev". */
	SharedMailBox<InfoFrame> prevFwMeFst;
	SharedMailBox<InfoFrame> prevFwMmFst;
	SharedMailBox<InfoFrame> prevMeAFst;
	SharedMailBox<InfoFrame> prevMeBFst;
	SharedMailBox<InfoFrame> prevPrevMeAFst;
	SharedMailBox<InfoFrame> prevPrevMeBFst;
	SharedMailBox<InfoFrame> prevMeAMv1;
	SharedMailBox<InfoFrame> prevMeBMv0;
	SharedMailBox<InfoFrame> prevMeL0;
	SharedMailBox<InfoFrame> prevMeL1;
	SharedMailBox<InfoFrame> preDipTnrso;
	SharedMailBox<InfoFrame> prevImg4oF0;
	SharedMailBox<InfoFrame> prevImg4oF1;
	std::vector<SharedMailBox<InfoFrame>> prevDipTnrwo;
};

struct TuningFrames {
	/* Inputs generated by IPA */
	SharedMailBox<InfoFrame> trMeTun; // Tuning of ME for stage HW_LTR_ME_L1
	SharedMailBox<InfoFrame> meATun; // Tuning of ME for stage HW_ME_3PASS_MODE_0
	SharedMailBox<InfoFrame> meBTun; // Tuning of ME for stage HW_ME_3PASS_MODE_1
	SharedMailBox<InfoFrame> meMil; // Tuning of ME for stage HW_ME_3PASS_MODE_1
	SharedMailBox<InfoFrame> ltrTunF1; // Tuning of TR for stage HW_LTR_F1
	SharedMailBox<InfoFrame> ltrTunF4; // Tuning of TR for stage HW_LTR_F4
	SharedMailBox<InfoFrame> trTunF1; // Tuning of TR for stage HW_TR_F1
	SharedMailBox<InfoFrame> trTunF4; // Tuning of TR for stage HW_TR_F4
	SharedMailBox<InfoFrame> ltrTunVbi; // Tuning of LTR for stage HW_LTR_VBI
	SharedMailBox<InfoFrame> wpeTun; // Tuning of WPE for stage HW_WPE_W_F*
	std::vector<SharedMailBox<InfoFrame>> dipTun; // Tuning of DIP for each stages
};

struct MeFrames {
	struct {
		SharedMailBox<InfoFrame> prevFwMeFst;
		SharedMailBox<InfoFrame> prevFwMmFst;
		SharedMailBox<InfoFrame> prevMeAFst;
		SharedMailBox<InfoFrame> prevMeBFst;

		SharedMailBox<InfoFrame> prevPrevMeAFst;
		SharedMailBox<InfoFrame> prevPrevMeBFst;

		SharedMailBox<InfoFrame> prevMeAMv1;
		SharedMailBox<InfoFrame> prevMeBMv0;
		SharedMailBox<InfoFrame> prevMeL0;
		SharedMailBox<InfoFrame> prevMeL1;
		SharedMailBox<InfoFrame> meL0;

		SharedMailBox<InfoFrame> trMeTun;
		SharedMailBox<InfoFrame> meATun;
		SharedMailBox<InfoFrame> meBTun;

		SharedMailBox<InfoFrame> fwMeFst;
		SharedMailBox<InfoFrame> fwMmFst;
		SharedMailBox<InfoFrame> fwMmRst;
		SharedMailBox<InfoFrame> meMil;
	} in;
	struct {
		SharedMailBox<InfoFrame> meL1;
		SharedMailBox<InfoFrame> meAMv0;
		SharedMailBox<InfoFrame> meAMv1;
		SharedMailBox<InfoFrame> meAFst;
		SharedMailBox<InfoFrame> meAFmb0;
		SharedMailBox<InfoFrame> meAFmb1;
		SharedMailBox<InfoFrame> meALmi;
		SharedMailBox<InfoFrame> meBMv0;
		SharedMailBox<InfoFrame> meBMv1;
		SharedMailBox<InfoFrame> meBFst;
		SharedMailBox<InfoFrame> meBFmb0;
		SharedMailBox<InfoFrame> meBFmb1;
		SharedMailBox<InfoFrame> meBLmi;
		SharedMailBox<InfoFrame> meConf0;
		std::vector<SharedMailBox<InfoFrame>> meMmap;
	} out;
};

struct MeBFrames {
	struct {
		SharedMailBox<InfoFrame> prevMeL0;
		SharedMailBox<InfoFrame> prevMeL1;
		SharedMailBox<InfoFrame> meL0;
		SharedMailBox<InfoFrame> meBTun;
		SharedMailBox<InfoFrame> meMil;
	} in;
	struct {
		SharedMailBox<InfoFrame> meL1;
		SharedMailBox<InfoFrame> meAMv0;
		SharedMailBox<InfoFrame> meAFmb0;
		SharedMailBox<InfoFrame> meAFmb1;

		SharedMailBox<InfoFrame> meBMv0;
		SharedMailBox<InfoFrame> meBMv1;
		SharedMailBox<InfoFrame> meBFst;
		SharedMailBox<InfoFrame> meBFmb0;
		SharedMailBox<InfoFrame> meBFmb1;
		SharedMailBox<InfoFrame> meBLmi;
		SharedMailBox<InfoFrame> meConf0;
		std::vector<SharedMailBox<InfoFrame>> meMmap;
	} out;
};

struct TrFrames {
	struct {
		SharedMailBox<InfoFrame> p1F1;
		SharedMailBox<InfoFrame> trTunF1;
		SharedMailBox<InfoFrame> trTunF4;
		SharedMailBox<InfoFrame> meConf0;
		std::vector<SharedMailBox<InfoFrame>> meMmap;
	} in;
	struct {
		SharedMailBox<InfoFrame> trawStt;
		std::vector<SharedMailBox<InfoFrame>> dipImgi;
		SharedMailBox<InfoFrame> meConf4;
		SharedMailBox<InfoFrame> meConf5;
	} out;
};

struct Dip1Frames {
	struct {
		SharedMailBox<InfoFrame> ltrTunF1;
		SharedMailBox<InfoFrame> ltrTunF4;
		SharedMailBox<InfoFrame> ltrTunVbi;
		SharedMailBox<InfoFrame> wpeTun;
		std::vector<SharedMailBox<InfoFrame>> dipTun;
		SharedMailBox<InfoFrame> preDipTnrso;
		SharedMailBox<InfoFrame> prevImg4oF0;
		SharedMailBox<InfoFrame> prevImg4oF1;
		std::vector<SharedMailBox<InfoFrame>> prevDipTnrwo;
	} in;
	struct {
		SharedMailBox<InfoFrame> tnrlfdi;
		SharedMailBox<InfoFrame> dipTnrso;
		std::vector<SharedMailBox<InfoFrame>> reci;
		std::vector<SharedMailBox<InfoFrame>> img3o;
		std::vector<SharedMailBox<InfoFrame>> dipTnrwi;
		std::vector<SharedMailBox<InfoFrame>> dipTnrwo;
		std::vector<SharedMailBox<InfoFrame>> dipTnrmi;
		std::vector<SharedMailBox<InfoFrame>> dipTnrmo;
		std::vector<SharedMailBox<InfoFrame>> wpeVeci;
		std::vector<SharedMailBox<InfoFrame>> dipVbi;
		std::vector<SharedMailBox<InfoFrame>> dipVipi;
		std::vector<SharedMailBox<InfoFrame>> dipImgi;
		std::vector<SharedMailBox<InfoFrame>> dipTnrci;
		std::vector<SharedMailBox<InfoFrame>> meMmap;
		SharedMailBox<InfoFrame> img4oF1;
		SharedMailBox<InfoFrame> swHist;
	} out;
};

struct Dip2Frames {
	struct {
		std::vector<SharedMailBox<InfoFrame>> dipTun;
		SharedMailBox<InfoFrame> prevImg4oF0;
		SharedMailBox<InfoFrame> tnrlfdi;
		std::vector<SharedMailBox<InfoFrame>> reci;
		std::vector<SharedMailBox<InfoFrame>> dipTnrwi;
		std::vector<SharedMailBox<InfoFrame>> dipTnrmi;
		std::vector<SharedMailBox<InfoFrame>> meMmap;
		std::vector<SharedMailBox<InfoFrame>> dipImgi;
		std::vector<SharedMailBox<InfoFrame>> dipTnrci;
	} in;
	struct {
		SharedMailBox<InfoFrame> img4oF0;
		SharedMailBox<InfoFrame> dipTnrso;
		std::vector<SharedMailBox<InfoFrame>> img3o;
		std::vector<SharedMailBox<InfoFrame>> dipTnrwo;
	} out;
};

struct MCNRFrames {
	MeFrames meFrames;
	TrFrames trFrames;
	Dip1Frames dip1Frames;
	Dip2Frames dip2Frames;

	FrameBuffer *videoOut1 = nullptr;
	FrameBuffer *videoOut2 = nullptr;
};

class McnrTasksManager
{
public:
	McnrTasksManager(
		ImgSysDevice *imgSys, DmaHeap *dmaHeap, OnDeviceTuner *odt);

	int configure(const Size yuvInputSize, const Size videoOut1Size,
		      const Size videoOut2Size);

	int start();
	int stop();

	int releaseBuffers();

	void makeMCNRFrames(MCNRFrames &mcnr,
			    MCNRPrevOutput &prev,
			    SharedMailBox<InfoFrame> &meL0,
			    SharedMailBox<InfoFrame> &p1F0,
			    SharedMailBox<InfoFrame> &p1F1,
			    FrameBuffer *videoOut1,
			    FrameBuffer *videoOut2);

	std::tuple<MeATask *, MeBTask *, TrTask *, Dip1Task *, Dip2Task *>
	makeMcnrTasks(MCNRFrames &mcnr, Scheduler *scheduler,
		      const std::string &id, Request *request,
		      uint32_t internalRequestId, ImgSysDevice *imgSys);

private:
	friend class Dip1Task;
	friend class Dip2Task;
	friend class TrTask;
	friend class MeATask;
	friend class MeBTask;
	friend MtkISP7CameraData;

	int configureBuffers();

	bool needCropTNC16x9_;

	Size yuvInputSize_;
	Size videoOut1Size_;
	Size videoOut2Size_;

	std::vector<Size> wtSizes;
	std::vector<Size> mcnrSizes;
	std::vector<Size> meMmapSizes;

	/* MCNR intermediate buffers' pools */
	InfoFramePool fwmeFst_;
	InfoFramePool fwmmFst;
	InfoFramePool fwmmRst_;
	InfoFramePool fwmmMil_;
	InfoFramePool fwmmGyro_;
	InfoFramePool meIn_;
	InfoFramePool meMv0_;
	InfoFramePool meMv1_;
	InfoFramePool meFst_;
	InfoFramePool meLmi_;
	InfoFramePool meFmb0_;
	InfoFramePool meFmb1_;
	InfoFramePool meMmap0_;
	InfoFramePool meMmap1_;
	InfoFramePool meMmap2_;
	InfoFramePool meMmap3_;
	InfoFramePool meConf0_;
	InfoFramePool meConf4_;
	InfoFramePool meConf5_;
	InfoFramePool trawStt_;
	InfoFramePool idi_;
	InfoFramePool tnrSo_;
	InfoFramePool img4oF0_;
	InfoFramePool img4oF1_;
	std::array<InfoFramePool, 7> wt_;
	std::array<InfoFramePool, 7> img3o_;
	std::array<InfoFramePool, 7> tnrmo_;
	std::array<InfoFramePool, 7> vbi_;

	/* Weak ptr for above pools for easier control */
	std::vector<InfoFramePool *> allBufferPools_;
	std::vector<InfoFramePool *> poolsWritenByCpu_;

	ImgSysDevice *imgSys_;
	DmaHeap *dmaHeap_;
	OnDeviceTuner *onDeviceTuner_;
};

class MeATask : public Task
{
public:
	MeATask(Scheduler *scheduler, const std::string &id,
		Request *request, uint32_t internalRequestId,
		ImgSysDevice *imgSys, MCNRFrames &mcnr, McnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	MeFrames frames_;

	uint32_t syncLtrMeA_;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	McnrTasksManager *manager_;
	ImgSysDevice *imgSys_;
};

class MeBTask : public Task
{
public:
	MeBTask(Scheduler *scheduler, const std::string &id,
		Request *request, uint32_t internalRequestId,
		ImgSysDevice *imgSys, MCNRFrames &mcnr, McnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	MeBFrames frames_;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	McnrTasksManager *manager_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
};

class TrTask : public Task
{
public:
	TrTask(Scheduler *scheduler, const std::string &id,
	       Request *request, uint32_t internalRequestId,
	       ImgSysDevice *imgSys, MCNRFrames &mcnr, McnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	TrFrames frames_;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	McnrTasksManager *manager_;
	ImgSysDevice *imgSys_;
};

class Dip1Task : public Task
{
public:
	Dip1Task(Scheduler *scheduler, const std::string &id,
		 Request *request, uint32_t internalRequestId,
		 ImgSysDevice *imgSys, MCNRFrames &mcnr, McnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	void setDipParams(StageEx &stage, unsigned int level);
	void setWpeParams(StageEx &stage, unsigned int level);

	uint32_t syncLtrDip_;
	uint32_t syncWpeDip_;

	Dip1Frames frames_;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	McnrTasksManager *manager_;
	ImgSysDevice *imgSys_;
};

class Dip2Task : public Task
{
public:
	Dip2Task(Scheduler *scheduler, const std::string &id,
		 Request *request, uint32_t internalRequestId,
		 ImgSysDevice *imgSys, MCNRFrames &mcnr, McnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	Dip2Frames frames_;

	FrameBuffer *videoOut1 = nullptr;
	FrameBuffer *videoOut2 = nullptr;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	McnrTasksManager *manager_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
};

} /* namespace libcamera */
