/*
 * Copyright (C) 2024, Google Inc.
 *
 * mfnr.h - MtkISP7 ImgSys Device Mutiple Frame Noise Reduction
 */

#pragma once

#include <memory>

#include "libcamera/internal/info_frame.h"
#include "libcamera/internal/mailbox.h"
#include "libcamera/internal/task_scheduler.h"

#include "../camsys/capture.h"
#include "pipeline/mtkisp7/camsys/capture.h"
#include "pipeline/mtkisp7/imgsys/const.h"
#include "pipeline/mtkisp7/odt/on_device_tuner.h"

#include "imgsys.h"

#define MFNR_QUEUE_SIZE 4
namespace libcamera {

class BfbldTask;
class McdsF1Task;
class BfmeTask;
class CalMeTask;
class DsTask;
class DsVbiTask;
class VbTask;
class MsbldTask;
class AfbldTask;
class MtkISP7CameraData;

struct MFNRPrevOutput {
	/* For the first frame, there is no previous outputs. valid = false
   * indicates that contents are empty. */
	bool valid = false;

	/* Generated by the previous frame's MFNR processing with the
   * corresponding names with the prefix "prev". */
	SharedMailBox<InfoFrame> prevMeAMv1;
	SharedMailBox<InfoFrame> prevMeBMv0;
	SharedMailBox<InfoFrame> prevMeL0;
	SharedMailBox<InfoFrame> prevMeL1;
	SharedMailBox<InfoFrame> preDipTnrso;
	SharedMailBox<InfoFrame> prevImg4oF0;
	SharedMailBox<InfoFrame> prevImg4oF1;
	std::vector<SharedMailBox<InfoFrame>> prevDipTnrwo;
};

struct BfbldFrames {
	std::vector<SharedMailBox<InfoFrame>> capturedRaws;
	struct {
		std::vector<SharedMailBox<InfoFrame>> timgi;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> p2stto;
		std::vector<SharedMailBox<InfoFrame>> img2o;
		std::vector<SharedMailBox<InfoFrame>> img3o;
	} out;
};

struct McdsF1Frames {
	struct {
		std::vector<SharedMailBox<InfoFrame>> wpe_wpei;
		std::vector<SharedMailBox<InfoFrame>> wpe_veci;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> wpe_wpeo;
		std::vector<SharedMailBox<InfoFrame>> ltyuv2o;
		std::vector<SharedMailBox<InfoFrame>> ltyuv3o;
		std::vector<SharedMailBox<InfoFrame>> ltyuv4o;
		std::vector<SharedMailBox<InfoFrame>> ltyuv5o;
	} out;
};

struct DsFrames {
	struct {
		std::vector<SharedMailBox<InfoFrame>> ltimgi;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> ltyuv2o;
		std::vector<SharedMailBox<InfoFrame>> ltyuv3o;
		std::vector<SharedMailBox<InfoFrame>> ltyuv4o;
	} out;
};

struct BfmeFrames {
	SharedMailBox<InfoFrame> tncso;
	struct {
		std::vector<SharedMailBox<InfoFrame>> imgi;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> img2o;
	} out;
};

struct DsVbiFrames {
	struct {
		std::vector<SharedMailBox<InfoFrame>> timgi;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> tyuv2o;
		std::vector<SharedMailBox<InfoFrame>> tyuv3o;
		std::vector<SharedMailBox<InfoFrame>> tyuv4o;
	} out;
};

struct MsbldFrames {
	struct {
		SharedMailBox<InfoFrame> vipi;
		SharedMailBox<InfoFrame> imgi;
		SharedMailBox<InfoFrame> tnrsi;
		SharedMailBox<InfoFrame> rec_dsi;
		SharedMailBox<InfoFrame> tnrci;
		SharedMailBox<InfoFrame> tnrwi;
		SharedMailBox<InfoFrame> tnrvbi;
		SharedMailBox<InfoFrame> tnrlfdi;
		SharedMailBox<InfoFrame> tnrmi;
		SharedMailBox<InfoFrame> tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame> img4o;
		SharedMailBox<InfoFrame> tnrwo;
		SharedMailBox<InfoFrame> tnrmo;
		SharedMailBox<InfoFrame> tnrso;
	} out;
};

struct AfbldFrames {
	SharedMailBox<InfoFrame> tncso;
	struct {
		std::vector<SharedMailBox<InfoFrame>> vipi;
		std::vector<SharedMailBox<InfoFrame>> imgi;
		std::vector<SharedMailBox<InfoFrame>> tnrsi;
		std::vector<SharedMailBox<InfoFrame>> rec_dsi;
		std::vector<SharedMailBox<InfoFrame>> tnrci;
		std::vector<SharedMailBox<InfoFrame>> tnrwi;
		std::vector<SharedMailBox<InfoFrame>> tnrvbi;
		std::vector<SharedMailBox<InfoFrame>> tnrlfdi;
		std::vector<SharedMailBox<InfoFrame>> tnrmi;
		std::vector<SharedMailBox<InfoFrame>> tunbufi;

	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> img3o;
		std::vector<SharedMailBox<InfoFrame>> img4o;
		std::vector<SharedMailBox<InfoFrame>> tnrmo;
		std::vector<SharedMailBox<InfoFrame>> wdmao;
		std::vector<SharedMailBox<InfoFrame>> tnrwo;
		std::vector<SharedMailBox<InfoFrame>> wroto;
		std::vector<SharedMailBox<InfoFrame>> tnrso;
	} out;
};

struct BssFrames {
	struct {
		SharedMailBox<InfoFrame> bssParamInfo;
		SharedMailBox<InfoFrame> bssDataGInfo;
		SharedMailBox<InfoFrame> bssVerInfo;
		SharedMailBox<InfoFrame> bssTuningInfo; // TODO: Harvey thinks this is output

		std::vector<SharedMailBox<InfoFrame>> bssFdMainInfo;
		std::vector<SharedMailBox<InfoFrame>> imgi;
		std::vector<SharedMailBox<InfoFrame>> bssFdInfo;
		std::vector<SharedMailBox<InfoFrame>> bssFaceInfo;
		std::vector<SharedMailBox<InfoFrame>> bssPosInfo;
	} in;
	struct {
		SharedMailBox<InfoFrame> bssOutDataInfo;
		SharedMailBox<std::vector<int>> bss_order;
	} out;
};

struct SwmeFrames {
	struct {
		std::vector<SharedMailBox<InfoFrame>> base_buf;
		std::vector<SharedMailBox<InfoFrame>> ref_buf;
		std::vector<SharedMailBox<InfoFrame>> bss_buf;
		std::vector<SharedMailBox<InfoFrame>> paramInInfo;
		std::vector<SharedMailBox<InfoFrame>> tuningInfo;
	} in;
	struct {
		std::vector<SharedMailBox<InfoFrame>> conf_map;
		std::vector<SharedMailBox<InfoFrame>> warpping_map;
		std::vector<SharedMailBox<InfoFrame>> mcmv;
		std::vector<SharedMailBox<InfoFrame>> paramOutInfo;
	} out;
};

struct MFNRFrames {
	BssFrames bssFrames;
	BfbldFrames bfbldFrames;
	BfmeFrames bfmeFrames;
	McdsF1Frames mcdsF1Frames;
	DsFrames dsFrames;
	DsVbiFrames dsVbiFramesV2;
	DsVbiFrames dsVbiFramesV5;
	struct {
		MsbldFrames msbldF0;
		MsbldFrames msbldF1;
		MsbldFrames msbldF2;
		MsbldFrames msbldF3;
		MsbldFrames msbldF4;
		MsbldFrames msbldF5;
		MsbldFrames msbldF6;
	} msbldFrames[2];
	AfbldFrames afbldF0;
	AfbldFrames afbldF1;
	AfbldFrames afbldF2;
	AfbldFrames afbldF3;
	AfbldFrames afbldF4;
	AfbldFrames afbldF5;
	AfbldFrames afbldF6;
	SwmeFrames swmeFrames;
	SharedMailBox<std::vector<int>> bss_order;
	FrameBuffer *still1Output = nullptr;
	FrameBuffer *still2Output = nullptr;
};

class MfnrTasksManager
{
public:
	MfnrTasksManager(ImgSysDevice *imgSys, DmaHeap *dmaHeap, OnDeviceTuner *odt);

	int configure(History<MfnrInput> *mfnrInput,
		      const Size &bayerInputSize,
		      const Size &yuvOutputSize1,
		      const Size &yuvOutputSize2,
		      const Size &videoOutputSize1,
		      const Size &videoOutputSize2,
		      const Size &confMapSize,
		      int sensor_idx);

	int start();
	int stop();
	int releaseBuffers();
	void releaseElasticBuffers();

	static bool mfnrPrecheck();

	static Size getSizeAligned(const Size &bayerInputSize);

	void makeMFNRFrames(MFNRFrames &mfnr,
			    uint32_t internalRequestId,
			    FrameBuffer *output1Frame,
			    FrameBuffer *output2Frame);
	std::vector<Size> mfnrSizes_;
	Size mfnrSize_aligned16_;
	std::tuple<BfbldTask *, BfmeTask *, McdsF1Task *, DsTask *, DsVbiTask *, MsbldTask *, MsbldTask *, AfbldTask *>
	makeMfnrTasks(MFNRFrames &mfnr, Scheduler *scheduler,
		      const std::string &id, Request *request,
		      uint32_t internalRequestId, ImgSysDevice *imgSys, PipelineHandler *pipe);

	Size confMapSize_;

private:
	friend class BfbldTask;
	friend class McdsF1Task;
	friend class BfmeTask;
	friend class CalMeTask;
	friend class DsTask;
	friend class DsVbiTask;
	friend class MsbldTask;
	friend class AfbldTask;
	friend MtkISP7CameraData;

	int configureBuffers();

	History<MfnrInput> *mfnrInput_;

	Size yuvOutputSize1_;
	Size yuvOutputSize2_;
	Size videoOutputSize1_;
	Size videoOutputSize2_;
	Size bayerInputSize_;
	int sensor_idx_;

	ImgSysDevice *imgSys_;
	DmaHeap *dmaHeap_;
	OnDeviceTuner *onDeviceTuner_;

	/* Weak ptr for above pools for easier control */
	std::vector<ElasticInfoFramePool *> allBufferPools_;

	/* MFNR intermediate buffers' pools */
	InfoFramePool p2sttoPool_;
	ElasticInfoFramePool yuvp010_1_1_pool_;
	ElasticInfoFramePool yuvp010_1_4_pool_aligned16_;
	ElasticInfoFramePool yuvp012_1_2_pool_;
	ElasticInfoFramePool yuvp012_1_4_pool_;
	ElasticInfoFramePool yuvp012_1_8_pool_;
	ElasticInfoFramePool yuvp012_1_16_pool_;
	ElasticInfoFramePool yuvp012_1_32_pool_;
	ElasticInfoFramePool yuvp012_1_64_pool_;
	ElasticInfoFramePool y8_1_1_pool_;
	ElasticInfoFramePool y8_1_2_pool_;
	ElasticInfoFramePool y8_1_4_pool_;
	InfoFramePool y8_1_4_pool_aligned16_;
	ElasticInfoFramePool y8_1_8_pool_;
	ElasticInfoFramePool y8_1_16_pool_;
	ElasticInfoFramePool y8_1_32_pool_;
	ElasticInfoFramePool fourBytes_pool_;
	ElasticInfoFramePool nv21_1_64_pool_;
	ElasticInfoFramePool nv12_wroto_pool_;

	// TODO, need to get fe from hw/sw
	std::vector<SharedMailBox<InfoFrame>> mcdsWpeVeci;
	int captureNum_;
	int blendNum_;
};

class BfbldTask : public Task
{
public:
	BfbldTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		  ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	BfbldFrames frames_;
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	SharedMailBox<std::vector<int>> bssOrder_;
};

class McdsF1Task : public Task
{
public:
	McdsF1Task(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		   ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	McdsF1Frames frames_;
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	SharedMailBox<std::vector<int>> bssOrder_;
};

class BfmeTask : public Task
{
public:
	BfmeTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		 ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	BfmeFrames frames_;
	SharedMailBox<std::vector<int>> bssOrder_;
};

class DsTask : public Task
{
public:
	DsTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
	       ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	DsFrames frames_;
	SharedMailBox<std::vector<int>> bssOrder_;
};

class DsVbiTask : public Task
{
public:
	DsVbiTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		  ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	DsVbiFrames dsVbiFramesV2_;
	DsVbiFrames dsVbiFramesV5_;
	SharedMailBox<std::vector<int>> bssOrder_;
};

class MsbldTask : public Task
{
public:
	MsbldTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		  ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager, int msbldIdx);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	MsbldFrames msbldF6_;
	MsbldFrames msbldF5_;
	MsbldFrames msbldF4_;
	MsbldFrames msbldF3_;
	MsbldFrames msbldF2_;
	MsbldFrames msbldF1_;
	MsbldFrames msbldF0_;
	SharedMailBox<std::vector<int>> bssOrder_;
	int msbldIdx_;
};

class AfbldTask : public Task
{
public:
	AfbldTask(Scheduler *scheduler, const std::string &id, Request *request, uint32_t internalRequestId,
		  ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager, PipelineHandler *pipe);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] uint32_t internalRequestId_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
	AfbldFrames afbldF0_;
	AfbldFrames afbldF1_;
	AfbldFrames afbldF2_;
	AfbldFrames afbldF3_;
	AfbldFrames afbldF4_;
	AfbldFrames afbldF5_;
	AfbldFrames afbldF6_;
	SharedMailBox<std::vector<int>> bssOrder_;

	FrameBuffer *stillOutput1_;
	FrameBuffer *stillOutput2_;

	PipelineHandler *pipe_;
};

} /* namespace libcamera */
