/*
 * Copyright (C) 2024, Google Inc.
 *
 * mfnr.h - MtkISP7 ImgSys Device Mutiple Frame Noise Reduction
 */

#pragma once

#include "libcamera/internal/info_frame.h"
#include "libcamera/internal/task_scheduler.h"

#include "pipeline/mtkisp7/odt/on_device_tuner.h"

#include "imgsys.h"

namespace libcamera {

struct MFNRPrevOutput {
	/* For the first frame, there is no previous outputs. valid = false
	 * indicates that contents are empty. */
	bool valid = false;

	/* Generated by the previous frame's MFNR processing with the
	 * corresponding names with the prefix "prev". */
	SharedMailBox<InfoFrame> prevMeAMv1;
	SharedMailBox<InfoFrame> prevMeBMv0;
	SharedMailBox<InfoFrame> prevMeL0;
	SharedMailBox<InfoFrame> prevMeL1;
	SharedMailBox<InfoFrame> preDipTnrso;
	SharedMailBox<InfoFrame> prevImg4oF0;
	SharedMailBox<InfoFrame> prevImg4oF1;
	std::vector<SharedMailBox<InfoFrame>> prevDipTnrwo;
};


struct MfnrFrames {

	FrameBuffer *videoOut1 = nullptr;
	FrameBuffer *videoOut2 = nullptr;
};

class MfnrTasksManager
{
public:
	MfnrTasksManager(
		ImgSysDevice *imgSys, DmaHeap *dmaHeap, OnDeviceTuner *odt);

	int configure(const Size yuvInputSize, const Size videoOut1Size,
		      const Size videoOut2Size);

	int start();
	int stop();

	int releaseBuffers();

	void makeMfnrFrames(MfnrFrames &mfnr,
			    MFNRPrevOutput &prev,
			    SharedMailBox<InfoFrame> &meL0,
			    SharedMailBox<InfoFrame> &p1F0,
			    SharedMailBox<InfoFrame> &p1F1,
			    FrameBuffer *videoOut1,
			    FrameBuffer *videoOut2);

private:

private:
	int configureBuffers();

	Size yuvInputSize_;
	Size videoOut1Size_;
	Size videoOut2Size_;

	ImgSysDevice *imgSys_;
	DmaHeap *dmaHeap_;
	OnDeviceTuner *onDeviceTuner_;

	std::vector<InfoFramePool *> allBufferPools_;
};

} /* namespace libcamera */