/*
 * Copyright (C) 2024, Google Inc.
 *
 * mfnr.h - MtkISP7 ImgSys Device Mutiple Frame Noise Reduction
 */

#pragma once

#include "libcamera/internal/info_frame.h"
#include "libcamera/internal/task_scheduler.h"

#include "pipeline/mtkisp7/odt/on_device_tuner.h"

#include "imgsys.h"

namespace libcamera {

class BfbldBaseTask;
class BfbldRefTask;
class BfmeTask;
class CalMeTask;
class DsTask;
class VbTask;
class MsblendingTask;

struct MFNRPrevOutput {
	/* For the first frame, there is no previous outputs. valid = false
	 * indicates that contents are empty. */
	bool valid = false;

	/* Generated by the previous frame's MFNR processing with the
	 * corresponding names with the prefix "prev". */
	SharedMailBox<InfoFrame> prevMeAMv1;
	SharedMailBox<InfoFrame> prevMeBMv0;
	SharedMailBox<InfoFrame> prevMeL0;
	SharedMailBox<InfoFrame> prevMeL1;
	SharedMailBox<InfoFrame> preDipTnrso;
	SharedMailBox<InfoFrame> prevImg4oF0;
	SharedMailBox<InfoFrame> prevImg4oF1;
	std::vector<SharedMailBox<InfoFrame>> prevDipTnrwo;
};

struct BfbldFrames {
	struct {
		SharedMailBox<InfoFrame>  timgi;
		SharedMailBox<InfoFrame>  tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame>  p2stto;
		SharedMailBox<InfoFrame>  img2o;
		SharedMailBox<InfoFrame>  img3o;
	} out;
};


struct DsFrames {
	struct {
		SharedMailBox<InfoFrame>  ltimgi;
		SharedMailBox<InfoFrame>  tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame>  ltyuv2o;
		SharedMailBox<InfoFrame>  ltyuv3o;
		SharedMailBox<InfoFrame>  ltyuv4o;
	} out;
};

struct BfmeFrames {
	struct {
		SharedMailBox<InfoFrame>  imgi;
		SharedMailBox<InfoFrame>  tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame>  img2o;
	} out;
};

struct McdsF1Frames {
	struct {
		SharedMailBox<InfoFrame>  wpe_wpei;
		SharedMailBox<InfoFrame>  wpe_veci;
		SharedMailBox<InfoFrame>  tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame>  wpe_wpeo;
		SharedMailBox<InfoFrame>  ltyuv2o;
		SharedMailBox<InfoFrame>  ltyuv3o;
		SharedMailBox<InfoFrame>  ltyuv4o;
		SharedMailBox<InfoFrame>  ltyuv5o;
	} out;
};


struct DsVbiFrames {
	struct {
		SharedMailBox<InfoFrame>  timgi;
		SharedMailBox<InfoFrame>  tunbufi;
	} in;
	struct {
		SharedMailBox<InfoFrame>  tyuv2o;
		SharedMailBox<InfoFrame>  tyuv3o;
		SharedMailBox<InfoFrame>  tyuv4o;
	} out;
};


struct MsbldFrames {
	struct {
		SharedMailBox<InfoFrame>  vipi;
		SharedMailBox<InfoFrame>  imgi;
		SharedMailBox<InfoFrame>  tnrsi;
		SharedMailBox<InfoFrame>  rec_dsi;
		SharedMailBox<InfoFrame>  tnrci;
		SharedMailBox<InfoFrame>  tnrwi;
		SharedMailBox<InfoFrame>  tnrvbi;
		SharedMailBox<InfoFrame>  tnrlfdi;
		SharedMailBox<InfoFrame>  tnrmi;
		SharedMailBox<InfoFrame>  tunbufi;

	} in;
	struct {
		SharedMailBox<InfoFrame>  img4o;
		SharedMailBox<InfoFrame>  tnrwo;
		SharedMailBox<InfoFrame>  tnrmo;
		SharedMailBox<InfoFrame>  tnrso;
	} out;
};

struct AfbldFrames {
	struct {
		SharedMailBox<InfoFrame>  vipi;
		SharedMailBox<InfoFrame>  imgi;
		SharedMailBox<InfoFrame>  tnrsi;
		SharedMailBox<InfoFrame>  rec_dsi;
		SharedMailBox<InfoFrame>  tnrci;
		SharedMailBox<InfoFrame>  tnrwi;
		SharedMailBox<InfoFrame>  tnrvbi;
		SharedMailBox<InfoFrame>  tnrlfdi;
		SharedMailBox<InfoFrame>  tnrmi;
		SharedMailBox<InfoFrame>  tunbufi;

	} in;
	struct {
		SharedMailBox<InfoFrame>  imgao;
		SharedMailBox<InfoFrame>  img3o;
		SharedMailBox<InfoFrame>  img4o;
		SharedMailBox<InfoFrame>  tnrwo;
		SharedMailBox<InfoFrame>  tnrmo;
		SharedMailBox<InfoFrame>  tnrso;
	} out;
};


struct MFNRFrames {

	BfbldFrames BfbldFrames;
	FrameBuffer *videoOut1 = nullptr;
	FrameBuffer *videoOut2 = nullptr;
};

class MfnrTasksManager
{
public:
	MfnrTasksManager(
		ImgSysDevice *imgSys, DmaHeap *dmaHeap, OnDeviceTuner *odt);

	int configure(const Size yuvInputSize, const Size videoOut1Size,
		      const Size videoOut2Size);

	int start();
	int stop();

	int releaseBuffers();

	void makeMfnrFrames(MFNRFrames &mfnr,
			    MFNRPrevOutput &prev,
			    SharedMailBox<InfoFrame> &meL0,
			    SharedMailBox<InfoFrame> &p1F0,
			    SharedMailBox<InfoFrame> &p1F1,
			    FrameBuffer *videoOut1,
			    FrameBuffer *videoOut2);

	std::tuple<BfbldBaseTask *,BfbldRefTask *, BfmeTask *, CalMeTask *, DsTask *, VbTask *, MsblendingTask *>
	makeMfnrTasks(MFNRFrames &mfnr, Scheduler *scheduler,
		      const std::string &id, Request *request,
		      ImgSysDevice *imgSys);

private:
	int configureBuffers();

	Size yuvInputSize_;
	Size videoOut1Size_;
	Size videoOut2Size_;

	ImgSysDevice *imgSys_;
	DmaHeap *dmaHeap_;
	OnDeviceTuner *onDeviceTuner_;

	std::vector<InfoFramePool *> allBufferPools_;

	int captureNum_;
	int blendNum_;
};

class BfbldBaseTask : public Task
{
public:
	BfbldBaseTask(Scheduler *scheduler, const std::string &id, Request *request,
		    ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	BfbldFrames frames_;
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;

};

class BfbldRefTask : public Task
{
public:
	BfbldRefTask(Scheduler *scheduler, const std::string &id, Request *request,
		    ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	MFNRFrames frames_;
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
};

class BfmeTask : public Task
{
public:
	BfmeTask(Scheduler *scheduler, const std::string &id, Request *request,
		 ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
};

class CalMeTask : public Task
{
public:
	CalMeTask(Scheduler *scheduler, const std::string &id, Request *request,
		  ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();

	uint32_t syncLtrMeA_;

	ImgSysRequestHelper requestHelper_;
	Request *request_;
	MfnrTasksManager *manager_;
	ImgSysDevice *imgSys_;
};

class DsTask : public Task
{
public:
	DsTask(Scheduler *scheduler, const std::string &id, Request *request,
	       ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
	MfnrTasksManager *manager_;
};

class VbTask : public Task
{
public:
	VbTask(Scheduler *scheduler, const std::string &id, Request *request,
	       ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;
	MfnrTasksManager *manager_;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
};

class MsblendingTask : public Task
{
public:
	MsblendingTask(Scheduler *scheduler, const std::string &id, Request *request,
		       ImgSysDevice *imgSys, MFNRFrames &mfnr, MfnrTasksManager *manager);

	void run() override;
	void notifyDone() override;

private:
	void allocateOutputBuffers();
	ImgSysRequestHelper requestHelper_;
	Request *request_;
	[[maybe_unused]] ImgSysDevice *imgSys_;
};

} /* namespace libcamera */