#include "platform/mtkisp7/mtkcam-chrom/custom/mt8188/hal/camera_db/include/BasicModule/list_begin_pub.h"

#define FOR_ALL_ELEMENTS(apply) \
/* APPLY_OPERATION(name, type, number, bit, ...) */ \
    apply(ME_NOISE_LEVEL                      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SRH_RNG                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SAD_COR                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_VAR_COR                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_RTO_TH1                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CNT_TH1                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_RTO_TH2                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CNT_TH2                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_RTO_TH3                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CNT_TH3                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_2_rsv_16                , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_CAND_ZERO_PNLTY             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_GMV_PNLTY              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_TMPR_PNLTY             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_1_rsv_24               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_RAND_INT_PNLTY         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_RAND_SUB_PNLTY         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_2_rsv_16               , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_CAND_BG_GMV_PNLTY_GAIN      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_BG_GMV_PNLTY_CLIP      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_FG_GMV_PNLTY_GAIN      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_FG_GMV_PNLTY_CLIP      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_INT_SMTH_PNLTY_VAR_H_TH, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_INT_SMTH_PNLTY_VAR_V_TH, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_INT_SMTH_PNLTY_GAIN_MAX, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_INT_SMTH_PNLTY_CLIP    , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_SUB_SMTH_PNLTY_GAIN    , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_SUB_SMTH_PNLTY_CLIP    , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_CAND_5_rsv_16               , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MVEP_BLK_WD                      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_GENERAL_rsv_8               , uint32_t   ,  1, 24,    ) /* */ \
    apply(ME_MVEP_MVBLD_MODE                  , uint32_t   ,  1,  2,    ) /* */ \
    apply(ME_MVEP_MVBLD_rsv_2                 , uint32_t   ,  1,  6,    ) /* */ \
    apply(ME_MVEP_MVBLD_ERR_OFST              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_MVBLD_rsv_16                , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MVEP_CJDET_TH1_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_TH2_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_MAX_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_TH1_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_TH2_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_MAX_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_TH1_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_TH2_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_MAX_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_CJDET_3_rsv_8               , uint32_t   ,  1, 24,    ) /* */ \
    apply(ME_MVEP_RVDET_TH1_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_TH2_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MAX_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MIN_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_TH1_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_TH2_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MAX_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MIN_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_TH1_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_TH2_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MAX_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_RVDET_MIN_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH1_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH2_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_MAX_A                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH1_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH2_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_MAX_B                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH1_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_TH2_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_MAX_C                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MVEP_SKDET_3_rsv_8               , uint32_t   ,  1, 24,    ) /* */ \
    apply(ME_CONF_MVIDX_DX_TH                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_DY_TH                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_DIV                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_COR                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_MAX                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_2_rsv_8               , uint32_t   ,  1, 24,    ) /* */ \
    apply(ME_CONF_SADIDX_RS                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_SADIDX_COR                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_SADIDX_MAX                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_SADIDX_1_rsv_24             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_VARIDX_RS                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_VARIDX_COR                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_VARIDX_MAX                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_VARIDX_1_rsv_24             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_DCIDX_RS                    , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_DCIDX_COR                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_DCIDX_MAX                   , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_DCIDX_1_rsv_24              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_FLT_OUTLIER_IDX_TH          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_FLT_SMTH_DT_MAX1            , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_FLT_SMTH_DT_MAX2            , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_FLT_rsv_24                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_ISM_MAX                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_ISM_TH1                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_ISM_TH2                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_ISM_rsv_24                  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_DC_COR          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_DC_RS           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_DC_MAX          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_DC_GAIN         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_VAR_TH1         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_VAR_TH2         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVIDX_SMCTP_2_rsv_16        , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_CONF_CTIDX_SML_TH1               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_CTIDX_rsv_8                 , uint32_t   ,  1, 24,    ) /* */ \
    apply(ME_CONF_MVEP_EN                     , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_CONF_OFST              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_VAR_WT_RS              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_1_rsv_24               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_VAR_WT_X1              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_VAR_WT_X2              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_VAR_WT_Y1              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_VAR_WT_Y2              , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_DC_WT_X1               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_DC_WT_X2               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_DC_WT_Y1               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_DC_WT_Y2               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_X1                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_X2                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_X3                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_Y1                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_Y2                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_Y3                 , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_CONF_MVEP_LMC_2_rsv_16           , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_SDGN_X1                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_X2                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_X3                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_X4                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_Y1                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_Y2                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_Y3                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_Y4                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_SDGN_EN_A                        , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_SDGN_EN_B                        , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_SDGN_EN_C                        , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_SDGN_EN_D                        , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_SDGN_3_rsv_4                     , uint32_t   ,  1, 28,    ) /* */ \
    apply(ME_LCL_DECONF_EN                    , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_LCL_DECONF_DLTVAR_EN             , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_LCL_DECONF_1_rsv_2               , uint32_t   ,  1, 30,    ) /* */ \
    apply(ME_LCL_DECONF_BG_BSS_RATIO          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LCL_DECONF_FD_BSS_RATIO          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LARGE_MV_TXTR_EN                 , uint32_t   ,  1,  1,    ) /* */ \
    apply(ME_LARGE_MV_1_rsv_1                 , uint32_t   ,  1, 15,    ) /* */ \
    apply(ME_LARGE_MV_THD                     , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LARGE_MV_SAD_THD                 , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LARGE_MV_RATIO                   , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LARGE_MV_TXTR_WEI                , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_LARGE_MV_TXTR_THD                , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_HG_rsv_0                    , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_HG_M1_CONF_TH               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_HG_M2_CONF_TH               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_TXTLVL_NOISE_TH_H           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_TXTLVL_NOISE_TH_V           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_TXTLVL_rsv_16               , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_TOTAL_PNLTY_GAIN            , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_NEW_GMV_PNLTY_MODE          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_GAIN_M1_A         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_CLIP_M1_A         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_MVDF_TH_M1_B      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_GAIN_M1_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_CLIP_M1_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_MVDF_TH_C1_B      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_GAIN_C1_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_CLIP_C1_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_MVDF_TH_M2_B      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_GAIN_M2_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_CLIP_M2_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_MVDF_TH_C2_B      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_GAIN_C2_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_PNLTY_CLIP_C2_B         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_NEW_SMTH_PNLTY_MODE         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_TXTLVL_TH0       , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_TXTLVL_TH1       , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_1_rsv_24         , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_RAND , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_RAND  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_RAND        , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_TEMP , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_TEMP  , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_TEMP        , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_GMV_M1, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_GMV_M1, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_GMV_M1      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_GMV_C1, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_GMV_C1, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_GMV_C1      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_GMV_M2, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_GMV_M2, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_GMV_M2      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_HIGH_GMV_C2, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_MVGAIN_LOW_GMV_C2, uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_CLIP_GMV_C2      , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_SMTH_PNLTY_6_rsv_16         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_MPME_GMV_CLST_MODE               , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_TXTLVL_TH          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_MVDF_TH            , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_1_rsv_24           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_B_RTO_TH           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_B_CNT_TH           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_F_RTO_TH           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_MPME_GMV_CLST_F_CNT_TH           , uint32_t   ,  1,  8,    ) /* */ \
    apply(ME_RSV_0_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_0_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_1_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_1_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_2_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_2_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_3_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_3_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_4_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_4_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_5_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_5_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_6_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_6_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_7_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_7_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_8_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_8_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_9_0                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_9_1                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_10_0                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_10_1                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_11_0                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_11_1                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_12_0                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_12_1                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_13_0                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_13_1                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_14_0                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_RSV_14_1                         , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_VERSION                          , uint32_t   ,  1, 16,    ) /* */ \
    apply(ME_VERSION_rsv_16                   , uint32_t   ,  1, 16,    ) /* */ \

#include "platform/mtkisp7/mtkcam-chrom/custom/mt8188/hal/camera_db/include/BasicModule/list_end_pub.h"
