#include "platform/mtkisp7/mtkcam-chrom/custom/mt8188/hal/camera_db/include/BasicModule/list_begin_pub.h"

#define FOR_ALL_ELEMENTS(apply) \
/* APPLY_OPERATION(name, type, number, bit, ...) */ \
    apply(bss_ver                             , uint32_t   ,  1,  2,    ) /* */ \
    apply(bss_ver_rsv_2                       , uint32_t   ,  1, 30,    ) /* */ \
    apply(scale_factor                        , uint32_t   ,  1,  8,    ) /* */ \
    apply(scale_factor_rsv_8                  , uint32_t   ,  1, 24,    ) /* */ \
    apply(clip_th0                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(clip_th0_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(clip_th1                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(clip_th1_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(clip_th2                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(clip_th2_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(clip_th3                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(clip_th3_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(zero_gmv                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(zero_gmv_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(adf_th                              , uint32_t   ,  1,  8,    ) /* */ \
    apply(adf_th_rsv_8                        , uint32_t   ,  1, 24,    ) /* */ \
    apply(sdf_th                              , uint32_t   ,  1,  8,    ) /* */ \
    apply(sdf_th_rsv_8                        , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_en                              , uint32_t   ,  1,  1,    ) /* */ \
    apply(ypf_en_rsv_1                        , uint32_t   ,  1, 31,    ) /* */ \
    apply(ypf_fac                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_fac_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_adj_th                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_adj_th_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_dfmed0                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_dfmed0_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_dfmed1                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_dfmed1_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th0                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th0_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th1                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th1_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th2                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th2_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th3                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th3_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th4                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th4_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th5                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th5_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th6                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th6_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(ypf_th7                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(ypf_th7_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(fd_en                               , uint32_t   ,  1,  1,    ) /* */ \
    apply(fd_en_rsv_1                         , uint32_t   ,  1, 31,    ) /* */ \
    apply(fd_fac                              , uint32_t   ,  1,  8,    ) /* */ \
    apply(fd_fac_rsv_8                        , uint32_t   ,  1, 24,    ) /* */ \
    apply(fd_fnum                             , uint32_t   ,  1,  4,    ) /* */ \
    apply(fd_fnum_rsv_4                       , uint32_t   ,  1, 28,    ) /* */ \
    apply(eye_en                              , uint32_t   ,  1,  1,    ) /* */ \
    apply(eye_en_rsv_1                        , uint32_t   ,  1, 31,    ) /* */ \
    apply(eye_cfth                            , uint32_t   ,  1,  8,    ) /* */ \
    apply(eye_cfth_rsv_8                      , uint32_t   ,  1, 24,    ) /* */ \
    apply(eye_ratio0                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(eye_ratio0_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(eye_ratio1                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(eye_ratio1_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(eye_fac                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(eye_fac_rsv_8                       , uint32_t   ,  1, 24,    ) /* */ \
    apply(FaceCVTh                            , uint32_t   ,  1,  7,    ) /* */ \
    apply(bss_faceCVTh_rsv_7                  , uint32_t   ,  1, 25,    ) /* */ \
    apply(GradThL                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(bss_grad_thL_rsv_8                  , uint32_t   ,  1, 24,    ) /* */ \
    apply(GradThH                             , uint32_t   ,  1,  8,    ) /* */ \
    apply(bss_grad_thH_rsv_8                  , uint32_t   ,  1, 24,    ) /* */ \
    apply(FaceAreaThL0                        , uint32_t   ,  1, 16,    ) /* */ \
    apply(faceareaThL0_rsv_16                 , uint32_t   ,  1, 16,    ) /* */ \
    apply(FaceAreaThL1                        , uint32_t   ,  1, 16,    ) /* */ \
    apply(faceareaThL1_rsv_16                 , uint32_t   ,  1, 16,    ) /* */ \
    apply(FaceAreaThH0                        , uint32_t   ,  1, 16,    ) /* */ \
    apply(faceareaThH0_rsv_16                 , uint32_t   ,  1, 16,    ) /* */ \
    apply(FaceAreaThH1                        , uint32_t   ,  1, 16,    ) /* */ \
    apply(faceareaThH1_rsv_16                 , uint32_t   ,  1, 16,    ) /* */ \
    apply(APLDeltaTh0                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh0_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh1                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh1_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh2                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh2_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh3                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh3_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh4                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh4_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh5                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh5_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh6                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh6_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh7                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh7_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh8                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh8_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh9                         , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh9_rsv_12                  , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh10                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh10_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh11                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh11_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh12                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh12_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh13                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh13_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh14                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh14_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh15                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh15_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh16                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh16_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh17                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh17_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh18                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh18_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh19                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh19_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh20                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh20_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh21                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh21_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh22                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh22_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh23                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh23_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh24                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh24_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh25                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh25_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh26                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh26_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh27                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh27_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh28                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh28_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh29                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh29_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh30                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh30_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh31                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh31_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(APLDeltaTh32                        , uint32_t   ,  1, 12,    ) /* */ \
    apply(apldeltaTh32_rsv_12                 , uint32_t   ,  1, 20,    ) /* */ \
    apply(GradRatioTh0                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh0_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh1                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh1_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh2                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh2_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh3                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh3_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh4                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh4_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh5                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh5_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh6                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh6_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(GradRatioTh7                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(gradRatioTh7_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(EyeDistThL                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(eyedistThL_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(EyeDistThH                          , uint32_t   ,  1,  8,    ) /* */ \
    apply(eyedistThH_rsv_8                    , uint32_t   ,  1, 24,    ) /* */ \
    apply(EyeMinWeight                        , uint32_t   ,  1, 15,    ) /* */ \
    apply(eyeminweight_rsv_15                 , uint32_t   ,  1, 17,    ) /* */ \
    apply(MF_BSS_ACTS_CLIP_TH0                , uint32_t   ,  1,  6,    ) /* */ \
    apply(acts_clip_th0_rsv_6                 , uint32_t   ,  1, 26,    ) /* */ \
    apply(MF_BSS_ACTS_CLIP_TH1                , uint32_t   ,  1,  6,    ) /* */ \
    apply(acts_clip_th1_rsv_6                 , uint32_t   ,  1, 26,    ) /* */ \
    apply(MF_BSS_BLEND_ISO_ThH                , uint32_t   ,  1, 14,    ) /* */ \
    apply(blend_iso_thH_rsv_14                , uint32_t   ,  1, 18,    ) /* */ \
    apply(MF_BSS_BLEND_ISO_ThL                , uint32_t   ,  1, 14,    ) /* */ \
    apply(blend_iso_thL_rsv_14                , uint32_t   ,  1, 18,    ) /* */ \
    apply(MF_BSS_Sharp_min_weight             , uint32_t   ,  1,  9,    ) /* */ \
    apply(sharpness_min_weight_rsv_9          , uint32_t   ,  1, 23,    ) /* */ \
    apply(AI_SHUTTER_MODE                     , uint32_t   ,  1,  1,    ) /* */ \
    apply(ai_shutter_mode_rsv_1               , uint32_t   ,  1, 31,    ) /* */ \
    apply(SCORE_WEIGHT0                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight0_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT1                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight1_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT2                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight2_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT3                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight3_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT4                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight4_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT5                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight5_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT6                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight6_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \
    apply(SCORE_WEIGHT7                       , uint32_t   ,  1, 15,    ) /* */ \
    apply(score_weight7_rsv_15                , uint32_t   ,  1, 17,    ) /* */ \

#include "platform/mtkisp7/mtkcam-chrom/custom/mt8188/hal/camera_db/include/BasicModule/list_end_pub.h"
