/* SPDX-License-Identifier: LGPL-2.1-or-later */
/*
 * Copyright (C) 2023, Google Inc.
 *
 * stage.h - MtkISP7 on device tuner stage enum.
 */
#pragma once

#include <map>
#include <string>

// todo(yerlandinata): yaml autogen

namespace libcamera {
enum class Stage {
	Default = 0,
	AFBLD_F0,
	AFBLD_F1,
	AFBLD_F2,
	AFBLD_F3,
	AFBLD_F4,
	AFBLD_F5,
	AFBLD_F6,
	AI_DEPTH,
	BFBLD_BASE,
	BFBLD_REF,
	BFME,
	BSS,
	DPE,
	DS,
	DS_VBI_V2,
	DS_VBI_V5,
	GF,
	LTR_Y2Y_Conf,
	LTR_Y2Y_F4,
	MCDS_F1,
	ME_1PASS,
	ME_3PASS_MM,
	ME_3PASS_MODE0,
	ME_3PASS_MODE1,
	ME_BATCH,
	ME_FW_MVP,
	MSBLD_F0,
	MSBLD_F1,
	MSBLD_F2,
	MSBLD_F3,
	MSBLD_F4,
	MSBLD_F5,
	MSBLD_F6,
	N3D,
	P1,
	P1_M,
	P1_S,
	P1_SE,
	P2_BOK_PV,
	P2_BOK_VR,
	P2_FM1_LR,
	P2_FM1_RL,
	P2_FM2_LR,
	P2_FM2_RL,
	P2_IDI,
	P2_MS_F0_H,
	P2_MS_F0_PQ_DIP,
	P2_MS_F0_Y_PQ_DIP,
	P2_MS_F1,
	P2_MS_F1_Y,
	P2_MS_F2,
	P2_MS_F2_Y,
	P2_MS_F3,
	P2_MS_F3_Y,
	P2_MS_F4,
	P2_MS_F_SMALL,
	P2_Single_debug,
	P2_Single_inline,
	P2_Single,
	P2_Y2Y_PQ_DIP,
	PQ_DIP_GUIDE,
	SWME,
	TR_FE1_M,
	TR_FE1_S,
	TR_FE2_M,
	TR_FE2_S,
	TR_ME_L0,
	TR_ME_L1,
	TR_P2_PQ_DIP,
	TR_R2Y,
	TR_Y2Y,
	TR_Y2Y_F1,
	TR_Y2Y_F4,
	Traw_3rd,
	WPE_Depth_ROT,
	WPE_GF_PV,
	WPE_GF_VR,
	WPE_LTR_ME_L0,
	LTR_VBI,
	WPE_LTR_Y2Y_F1,
	WPE_MAP_RZ_BLUR_PV,
	WPE_MAP_RZ_BLUR_VR,
	WPE_ME_L0,
	WPE_N3D_M,
	WPE_N3D_S,
	WPE_P2_PQDIP_MS_F0,
	WPE_TR_Y2Y_F1,
	WPE_WghtMap,
	WPEx2_P2_PQDIP_MS_F0,
	P2_MS_F1_dbg,
	P2_MS_F2_dbg,
	P2_MS_F3_dbg,
	P2_MS_F4_dbg,
	P2_MS_F5_dbg,
	WPE_P2_PQDIP_MS_F0_dbg,
	WPEx2_P2_PQDIP_MS_F0_dbg,
	Camsys_normal,
	Camysy_se,
	Depth_fe,
	Depth_fm,
	Bokeh,
	Raw2raw,
	Ainr_fe,
	Ainr_fm,
	Ainr_bpc,
	Raw2yuv,
	Yuv2yuv,
	Msf_y0,
	Msf_0,
	Msf_1,
	Msf_2,
	Msf_3,
	Msf_4,
	Msf_5,
	Msf_6,
	Msnr_yuv2yuv,
	Mdp,
	Yuv2yuv_reprocess,
	Pure_PQDIP,
	Raw_Pre_Bpc,
	BssYuv_Pre,
	RefYuv_Pre,
	BssYuv_Pre_Tnc,
	Yuv_Fe,
	Yuv_Fm,
	RAW_BeforeDRC,
	AIBC_RAW_PRE_BPC,
	AIBC_BSSYUV_PRE,
	AIBC_BSSYUV_PRE_TNC,
	AIBC_REFYUV_PRE,
	AIBC_FE,
	AIBC_FM,
	AIBC_DRC,
	AIBC_R2Y_14b_NNOut,
	AIBC_R2Y_16b_DRCOut,
	AIBC_R2Y_16b_NNOut,
	AIBlend,
	DRC,
	RAW_PRE_BPC,
	BSSYUV_PRE,
	BSSR2Y_PRE,
	BSSYUV_PRE_TNC,
	REFYUV_PRE,
	REFR2Y_PRE,
	WPE_XTR_ME_L0,
	XTR_ME_L0,
	LTR_ME_L1,
	WPE_LTR_ME_L0_L1,
	TR_DSMAP,
	TR_Y2Y_Conf,
	XTraw_3rd,
	XTraw_3rd_Raw,
	WPE_P2_DHZ_PQDIP_MS_F0,
	WPEx2_P2_DHZ_PQDIP_MS_F0,
	P2_MS_F1_3Layer,
	P2_DHZ_SL,
	DHZE_SL,
	TR_R2Y_DIP_PQDIP,
	TR_GAINMAP,
	TR_TNCS,
	PQ_DIP_GUIDE_IMG,
	WPE_DPEI_M,
	WPE_DPEI_S,
	WPE_DVS_DEPTH_ROT,
	WPE_DVS_CFM_ROT,
	WPE_AI_DEPTH_ROT,
	WPE_AI_DEPTH_CFM_ROT,
	WPE_AI_DEPTH_PRE,
	WPE_GUIDE_IMG_PRE,
	WPE_BLUR_PV,
	WPE_BLUR_VR,
	PS_LIB,
	WPE_PRE,
	WPE_AINR_FRAME,
	XTR_MS,
	TR_R2Y_MS,
	P1_3rd,
	TR_G2Y_3rd,
	BSSR2Y_2_PRE,
	BSSYUV_2_PRE_TNC,
	REFR2Y_2_PRE,
	TR_R2R_3rd,
	TR_Y2Y_P2_PQDIP_3rd,
	WPE_RSRAW,
	MSTM,
	IMAGE_SELECTION_2,
	WPE_PQDIP,
	VAINR_INIT,
	VAINR_AUXI,
	VAINR_CORE,
	NUM,
};

const std::map<Stage, std::string> kStageStrMap = {
	{ Stage::Default, "Default" },
	{ Stage::AFBLD_F0, "AFBLD_F0" },
	{ Stage::AFBLD_F1, "AFBLD_F1" },
	{ Stage::AFBLD_F2, "AFBLD_F2" },
	{ Stage::AFBLD_F3, "AFBLD_F3" },
	{ Stage::AFBLD_F4, "AFBLD_F4" },
	{ Stage::AFBLD_F5, "AFBLD_F5" },
	{ Stage::AFBLD_F6, "AFBLD_F6" },
	{ Stage::AI_DEPTH, "AI_DEPTH" },
	{ Stage::BFBLD_BASE, "BFBLD_BASE" },
	{ Stage::BFBLD_REF, "BFBLD_REF" },
	{ Stage::BFME, "BFME" },
	{ Stage::BSS, "BSS" },
	{ Stage::DPE, "DPE" },
	{ Stage::DS, "DS" },
	{ Stage::DS_VBI_V2, "DS_VBI_V2" },
	{ Stage::DS_VBI_V5, "DS_VBI_V5" },
	{ Stage::GF, "GF" },
	{ Stage::LTR_Y2Y_Conf, "LTR_Y2Y_Conf" },
	{ Stage::LTR_Y2Y_F4, "LTR_Y2Y_F4" },
	{ Stage::MCDS_F1, "MCDS_F1" },
	{ Stage::ME_1PASS, "ME_1PASS" },
	{ Stage::ME_3PASS_MM, "ME_3PASS_MM" },
	{ Stage::ME_3PASS_MODE0, "ME_3PASS_MODE0" },
	{ Stage::ME_3PASS_MODE1, "ME_3PASS_MODE1" },
	{ Stage::ME_BATCH, "ME_BATCH" },
	{ Stage::ME_FW_MVP, "ME_FW_MVP" },
	{ Stage::MSBLD_F0, "MSBLD_F0" },
	{ Stage::MSBLD_F1, "MSBLD_F1" },
	{ Stage::MSBLD_F2, "MSBLD_F2" },
	{ Stage::MSBLD_F3, "MSBLD_F3" },
	{ Stage::MSBLD_F4, "MSBLD_F4" },
	{ Stage::MSBLD_F5, "MSBLD_F5" },
	{ Stage::MSBLD_F6, "MSBLD_F6" },
	{ Stage::N3D, "N3D" },
	{ Stage::P1, "P1" },
	{ Stage::P1_M, "P1_M" },
	{ Stage::P1_S, "P1_S" },
	{ Stage::P1_SE, "P1_SE" },
	{ Stage::P2_BOK_PV, "P2_BOK_PV" },
	{ Stage::P2_BOK_VR, "P2_BOK_VR" },
	{ Stage::P2_FM1_LR, "P2_FM1_LR" },
	{ Stage::P2_FM1_RL, "P2_FM1_RL" },
	{ Stage::P2_FM2_LR, "P2_FM2_LR" },
	{ Stage::P2_FM2_RL, "P2_FM2_RL" },
	{ Stage::P2_IDI, "P2_IDI" },
	{ Stage::P2_MS_F0_H, "P2_MS_F0_H" },
	{ Stage::P2_MS_F0_PQ_DIP, "P2_MS_F0_PQ_DIP" },
	{ Stage::P2_MS_F0_Y_PQ_DIP, "P2_MS_F0_Y_PQ_DIP" },
	{ Stage::P2_MS_F1, "P2_MS_F1" },
	{ Stage::P2_MS_F1_Y, "P2_MS_F1_Y" },
	{ Stage::P2_MS_F2, "P2_MS_F2" },
	{ Stage::P2_MS_F2_Y, "P2_MS_F2_Y" },
	{ Stage::P2_MS_F3, "P2_MS_F3" },
	{ Stage::P2_MS_F3_Y, "P2_MS_F3_Y" },
	{ Stage::P2_MS_F4, "P2_MS_F4" },
	{ Stage::P2_MS_F_SMALL, "P2_MS_F_SMALL" },
	{ Stage::P2_Single_debug, "P2_Single_debug" },
	{ Stage::P2_Single_inline, "P2_Single_inline" },
	{ Stage::P2_Single, "P2_Single" },
	{ Stage::P2_Y2Y_PQ_DIP, "P2_Y2Y_PQ_DIP" },
	{ Stage::PQ_DIP_GUIDE, "PQ_DIP_GUIDE" },
	{ Stage::SWME, "SWME" },
	{ Stage::TR_FE1_M, "TR_FE1_M" },
	{ Stage::TR_FE1_S, "TR_FE1_S" },
	{ Stage::TR_FE2_M, "TR_FE2_M" },
	{ Stage::TR_FE2_S, "TR_FE2_S" },
	{ Stage::TR_ME_L0, "TR_ME_L0" },
	{ Stage::TR_ME_L1, "TR_ME_L1" },
	{ Stage::TR_P2_PQ_DIP, "TR_P2_PQ_DIP" },
	{ Stage::TR_R2Y, "TR_R2Y" },
	{ Stage::TR_Y2Y, "TR_Y2Y" },
	{ Stage::TR_Y2Y_F1, "TR_Y2Y_F1" },
	{ Stage::TR_Y2Y_F4, "TR_Y2Y_F4" },
	{ Stage::Traw_3rd, "Traw_3rd" },
	{ Stage::WPE_Depth_ROT, "WPE_Depth_ROT" },
	{ Stage::WPE_GF_PV, "WPE_GF_PV" },
	{ Stage::WPE_GF_VR, "WPE_GF_VR" },
	{ Stage::WPE_LTR_ME_L0, "WPE_LTR_ME_L0" },
	{ Stage::LTR_VBI, "LTR_VBI" },
	{ Stage::WPE_LTR_Y2Y_F1, "WPE_LTR_Y2Y_F1" },
	{ Stage::WPE_MAP_RZ_BLUR_PV, "WPE_MAP_RZ_BLUR_PV" },
	{ Stage::WPE_MAP_RZ_BLUR_VR, "WPE_MAP_RZ_BLUR_VR" },
	{ Stage::WPE_ME_L0, "WPE_ME_L0" },
	{ Stage::WPE_N3D_M, "WPE_N3D_M" },
	{ Stage::WPE_N3D_S, "WPE_N3D_S" },
	{ Stage::WPE_P2_PQDIP_MS_F0, "WPE_P2_PQDIP_MS_F0" },
	{ Stage::WPE_TR_Y2Y_F1, "WPE_TR_Y2Y_F1" },
	{ Stage::WPE_WghtMap, "WPE_WghtMap" },
	{ Stage::WPEx2_P2_PQDIP_MS_F0, "WPEx2_P2_PQDIP_MS_F0" },
	{ Stage::P2_MS_F1_dbg, "P2_MS_F1_dbg" },
	{ Stage::P2_MS_F2_dbg, "P2_MS_F2_dbg" },
	{ Stage::P2_MS_F3_dbg, "P2_MS_F3_dbg" },
	{ Stage::P2_MS_F4_dbg, "P2_MS_F4_dbg" },
	{ Stage::P2_MS_F5_dbg, "P2_MS_F5_dbg" },
	{ Stage::WPE_P2_PQDIP_MS_F0_dbg, "WPE_P2_PQDIP_MS_F0_dbg" },
	{ Stage::WPEx2_P2_PQDIP_MS_F0_dbg, "WPEx2_P2_PQDIP_MS_F0_dbg" },
	{ Stage::Camsys_normal, "Camsys_normal" },
	{ Stage::Camysy_se, "Camysy_se" },
	{ Stage::Depth_fe, "Depth_fe" },
	{ Stage::Depth_fm, "Depth_fm" },
	{ Stage::Bokeh, "Bokeh" },
	{ Stage::Raw2raw, "Raw2raw" },
	{ Stage::Ainr_fe, "Ainr_fe" },
	{ Stage::Ainr_fm, "Ainr_fm" },
	{ Stage::Ainr_bpc, "Ainr_bpc" },
	{ Stage::Raw2yuv, "Raw2yuv" },
	{ Stage::Yuv2yuv, "Yuv2yuv" },
	{ Stage::Msf_y0, "Msf_y0" },
	{ Stage::Msf_0, "Msf_0" },
	{ Stage::Msf_1, "Msf_1" },
	{ Stage::Msf_2, "Msf_2" },
	{ Stage::Msf_3, "Msf_3" },
	{ Stage::Msf_4, "Msf_4" },
	{ Stage::Msf_5, "Msf_5" },
	{ Stage::Msf_6, "Msf_6" },
	{ Stage::Msnr_yuv2yuv, "Msnr_yuv2yuv" },
	{ Stage::Mdp, "Mdp" },
	{ Stage::Yuv2yuv_reprocess, "Yuv2yuv_reprocess" },
	{ Stage::Pure_PQDIP, "Pure_PQDIP" },
	{ Stage::Raw_Pre_Bpc, "Raw_Pre_Bpc" },
	{ Stage::BssYuv_Pre, "BssYuv_Pre" },
	{ Stage::RefYuv_Pre, "RefYuv_Pre" },
	{ Stage::BssYuv_Pre_Tnc, "BssYuv_Pre_Tnc" },
	{ Stage::Yuv_Fe, "Yuv_Fe" },
	{ Stage::Yuv_Fm, "Yuv_Fm" },
	{ Stage::RAW_BeforeDRC, "RAW_BeforeDRC" },
	{ Stage::AIBC_RAW_PRE_BPC, "AIBC_RAW_PRE_BPC" },
	{ Stage::AIBC_BSSYUV_PRE, "AIBC_BSSYUV_PRE" },
	{ Stage::AIBC_BSSYUV_PRE_TNC, "AIBC_BSSYUV_PRE_TNC" },
	{ Stage::AIBC_REFYUV_PRE, "AIBC_REFYUV_PRE" },
	{ Stage::AIBC_FE, "AIBC_FE" },
	{ Stage::AIBC_FM, "AIBC_FM" },
	{ Stage::AIBC_DRC, "AIBC_DRC" },
	{ Stage::AIBC_R2Y_14b_NNOut, "AIBC_R2Y_14b_NNOut" },
	{ Stage::AIBC_R2Y_16b_DRCOut, "AIBC_R2Y_16b_DRCOut" },
	{ Stage::AIBC_R2Y_16b_NNOut, "AIBC_R2Y_16b_NNOut" },
	{ Stage::AIBlend, "AIBlend" },
	{ Stage::DRC, "DRC" },
	{ Stage::RAW_PRE_BPC, "RAW_PRE_BPC" },
	{ Stage::BSSYUV_PRE, "BSSYUV_PRE" },
	{ Stage::BSSR2Y_PRE, "BSSR2Y_PRE" },
	{ Stage::BSSYUV_PRE_TNC, "BSSYUV_PRE_TNC" },
	{ Stage::REFYUV_PRE, "REFYUV_PRE" },
	{ Stage::REFR2Y_PRE, "REFR2Y_PRE" },
	{ Stage::WPE_XTR_ME_L0, "WPE_XTR_ME_L0" },
	{ Stage::XTR_ME_L0, "XTR_ME_L0" },
	{ Stage::LTR_ME_L1, "LTR_ME_L1" },
	{ Stage::WPE_LTR_ME_L0_L1, "WPE_LTR_ME_L0_L1" },
	{ Stage::TR_DSMAP, "TR_DSMAP" },
	{ Stage::TR_Y2Y_Conf, "TR_Y2Y_Conf" },
	{ Stage::XTraw_3rd, "XTraw_3rd" },
	{ Stage::XTraw_3rd_Raw, "XTraw_3rd_Raw" },
	{ Stage::WPE_P2_DHZ_PQDIP_MS_F0, "WPE_P2_DHZ_PQDIP_MS_F0" },
	{ Stage::WPEx2_P2_DHZ_PQDIP_MS_F0, "WPEx2_P2_DHZ_PQDIP_MS_F0" },
	{ Stage::P2_MS_F1_3Layer, "P2_MS_F1_3Layer" },
	{ Stage::P2_DHZ_SL, "P2_DHZ_SL" },
	{ Stage::DHZE_SL, "DHZE_SL" },
	{ Stage::TR_R2Y_DIP_PQDIP, "TR_R2Y_DIP_PQDIP" },
	{ Stage::TR_GAINMAP, "TR_GAINMAP" },
	{ Stage::TR_TNCS, "TR_TNCS" },
	{ Stage::PQ_DIP_GUIDE_IMG, "PQ_DIP_GUIDE_IMG" },
	{ Stage::WPE_DPEI_M, "WPE_DPEI_M" },
	{ Stage::WPE_DPEI_S, "WPE_DPEI_S" },
	{ Stage::WPE_DVS_DEPTH_ROT, "WPE_DVS_DEPTH_ROT" },
	{ Stage::WPE_DVS_CFM_ROT, "WPE_DVS_CFM_ROT" },
	{ Stage::WPE_AI_DEPTH_ROT, "WPE_AI_DEPTH_ROT" },
	{ Stage::WPE_AI_DEPTH_CFM_ROT, "WPE_AI_DEPTH_CFM_ROT" },
	{ Stage::WPE_AI_DEPTH_PRE, "WPE_AI_DEPTH_PRE" },
	{ Stage::WPE_GUIDE_IMG_PRE, "WPE_GUIDE_IMG_PRE" },
	{ Stage::WPE_BLUR_PV, "WPE_BLUR_PV" },
	{ Stage::WPE_BLUR_VR, "WPE_BLUR_VR" },
	{ Stage::PS_LIB, "PS_LIB" },
	{ Stage::WPE_PRE, "WPE_PRE" },
	{ Stage::WPE_AINR_FRAME, "WPE_AINR_FRAME" },
	{ Stage::XTR_MS, "XTR_MS" },
	{ Stage::TR_R2Y_MS, "TR_R2Y_MS" },
	{ Stage::P1_3rd, "P1_3rd" },
	{ Stage::TR_G2Y_3rd, "TR_G2Y_3rd" },
	{ Stage::BSSR2Y_2_PRE, "BSSR2Y_2_PRE" },
	{ Stage::BSSYUV_2_PRE_TNC, "BSSYUV_2_PRE_TNC" },
	{ Stage::REFR2Y_2_PRE, "REFR2Y_2_PRE" },
	{ Stage::TR_R2R_3rd, "TR_R2R_3rd" },
	{ Stage::TR_Y2Y_P2_PQDIP_3rd, "TR_Y2Y_P2_PQDIP_3rd" },
	{ Stage::WPE_RSRAW, "WPE_RSRAW" },
	{ Stage::MSTM, "MSTM" },
	{ Stage::IMAGE_SELECTION_2, "IMAGE_SELECTION_2" },
	{ Stage::WPE_PQDIP, "WPE_PQDIP" },
	{ Stage::VAINR_INIT, "VAINR_INIT" },
	{ Stage::VAINR_AUXI, "VAINR_AUXI" },
	{ Stage::VAINR_CORE, "VAINR_CORE" },
	{ Stage::NUM, "NUM" },
};

const std::map<std::string, Stage> kStrStageMap =
	[] {
		std::map<std::string, Stage> result;
		for (const auto &[stage, name] : kStageStrMap) {
			result[name] = stage;
		}
		return result;
	}();

} // namespace libcamera
